### ISSUE TITLE
Hairline

### ISSUE THREAD

**Issue by miszokienka** [Cracert/QGIS-trans-PL#100]
Pozwoliłem sobie zmienić **Hairline** na **cienka linia**, bo do tej pory było nieprzetłumaczone, a wg słowników _Hairline_ ma znaczenia: _(Noun) linia włosów, krawędź zarostu; cienka linia; lina z włosia;_ - odrzuciłem te z włosami, ale jeśli chcecie to możemy zrobić głosowanie ;)

**Comment by borysiasty** [comment]
Czyli teraz chyba jest tak?
**szerokość linii:** ``cienka linia``

Może lepiej **najcieńsza** albo **minimalna**? 
Względnie: *cieniutka, jak włos, niczem włos, jeno włos*... :D

PS. To Ty tak dałeś czadu, że mamy już tylko 3581 (18,6%) nieprzetłumaczonych tekstów? Jak korespondowaliśmy tydzień temu, było ich ponad 4200 :)

**Comment by borysiasty** [comment]
@all: Etykietą ``proposal`` oznaczam te bilety, w których jest już jakaś propozycja rozwiązania problemu. Jeśli ktoś z Was uważa, że jest trafna (albo zainspiruje Cię do czegoś lepszego), to po prostu zmień w Transifeksie i zamykaj. Nie ma co trzymać otwartych tiketów w nieskończoność.

**Comment by alinager** [comment]
Hairline to linia włosowa - to jest stosowana w języku polskim nazwa.

**Comment by miszokienka** [comment]
Aaa, zmieniłem jeszcze tłumaczenie _stroke width_ z **szerokość linii** na **szerokość obrysu**, bo wg mnie tak znacznie lepiej oddaje kontekst, o którą linię chodzi. Są też wyrażenia z _line width_ i tam się pokazuje teraz, tak jak napisałeś Borys, czyli **szerokość linii:** `cienka linia`.

Czyli **linia włosowa**? Będzie to zrozumiałe?

P.S. Tak, to ja ;)

**Comment by borysiasty** [comment]
Włośnica. Włosiennica. Ja się nie znam na ludziach, ale jak dla mnie *linia włosowa* jest dość intuicyjne.

**Comment by miszokienka** [comment]
Zmienione na `linia włosowa`.
