### ISSUE TITLE
Uwierzytelnianie

### ISSUE THREAD

**Issue by borysiasty** [Cracert/QGIS-trans-PL#101]
Wszystkich namawiam na korzystanie z portfela (aka bazy haseł), ale potem widzą te dwa kompletnie zaniedbane rozwijalne menu. Niestety metody uwierzytelniania to nie jest moja mocna strona. @miszokienka, znasz się może na tej terminologii? Również *Wallet* i *KeyRing* zawsze używam w oryginale, ewentualnie samozwańczo tłumaczę na *portfel*, ale nie wiem, czy ktoś to rozumie :) 

![zrzut_20181010_220428](https://user-images.githubusercontent.com/1000043/46763242-9257d780-ccd9-11e8-88d5-648627795792.png)
![zrzut_20181010_220351](https://user-images.githubusercontent.com/1000043/46763248-93890480-ccd9-11e8-8901-21b58b493d7e.png)

**Comment by miszokienka** [comment]
Zawsze gdy spotykam te stringi na swojej drodze, to myślę jak to ugryźć i przechodzę do innych. W końcu jednak nadejdzie taki czas, że nie będzie gdzie uciekać ;)
Na razie nie mam pomysłu. Nie bardzo się też na tym znam. Poszedłem sobie teraz na studia informatyczne, więc może mi się coś rozjaśni za jakiś czas w tym temacie.

**Comment by borysiasty** [comment]
Kolejna sprawa: na pierwszym zrzucie widać, jak mieszamy formy uwierzytelni**A**nie i uwierzytelni**E**nie. Trzeba by się zdecydować, którą stosujemy w nazwach metod. IMHO obie pasują tak samo...

**Comment by borysiasty** [comment]
Z grubsza zrobione
