### ISSUE TITLE
Liczby i ilości

### ISSUE THREAD

**Issue by Cracert** [Cracert/QGIS-trans-PL#102]
@miszokienka - Wykonałeś naprawdę kawał dobrej roboty - dzięki!

Pozwoliłem sobie pozostawić słowo `ilości` tylko w kontekście pamięci. W pozostałych przypadkach zmieniłem w tłumaczeniach na `liczbę`.

**Comment by miszokienka** [comment]
Z lekką uszczypliwością dodam, że ta `liczba` zamiast `ilość` to chyba po krakowsku jest. Sam miałem dylemat czy to poprawiać, bo mam w sobie półgóralską krew ;)
A na poważnie to mi zdecydowanie bardziej pasuje i bardziej po polsku brzmi `ilość` wszędzie gdzie się to odnosi do ilości obiektów, do czegoś co jest policzone, do określenia wielkości zbioru. `Liczba` mi tu jakoś nie pasuje... Miałem nawet ciągoty, żeby wcześniej zrobić zmianę `liczb` na `ilość`, ale nie starczyło mi czasu i zapału.
A pozostali? Co sądzicie o liczbach i ilościach?

**Comment by borysiasty** [comment]
Mówicie o jakichś konkretnych tekstach, czy mam przefiltrować wszystkie liczby i ilości w dowolnych przypadkach? 

Oczywiście Miś ma rację z tą policzalnością - rozróżnienie między liczbą a ilością jest jednoznaczne. 1024 jajka to liczba, a dwie wywrotki to ilość (jajek, bo zarazem liczba wywrotek).

**Comment by borysiasty** [comment]
To znaczy właśnie nie ma racji ;) Policzona jest liczba, a ilość jest zmierzona.

**Comment by borysiasty** [comment]
Ok, przejrzałem ostatnie ~250 zmian i chyba widzę, o co chodzi. Niestety Miś nie ma racji. Policzalna jest liczba (jak sama nazwa wskazuje), a ilość jest odmierzalna. 100 jajek to liczba, a dwie wywrotki jajek to ilość (i zarazem liczba wywrotek). To jest jednoznaczna zasada.

**Comment by Cracert** [comment]
Jest wiele słów, które ostatnio zmienia swoje pierwotne znaczenie (np. funkcjonalność używana w znaczeniu `funkcja`). A przez powszechne użycie stają się nieformalnymi standardami. Dlatego rozumiem, że Cię to razi. 

Moje ostatnie zdanie to kolejny przykład zanikającego archaizmu. Większość napisałaby `Dlatego rozumiem, że Ciebie to razi`. Myślę, że wersje Misia staną się standardem szybciej niż myślimy. 

Ale chyba szkoda czasu na takie drobiazgi. Zamknijmy temat i jedźmy do przodu.

**Comment by miszokienka** [comment]
No cóż, nie zawsze Misie mają rację. Trochę się podszkoliłem dzięki Wam z polskiego i przyjmuję wersję, o której piszecie. Temat uważam za zamknięty. Nie ma chyba już potrzeby zwiększać **liczby** wpisów na ten temat ;)

**Comment by borysiasty** [comment]
Ten temat może zamknięty, ale @Cracert wsadził kij w mrowisko tym „drobiazgiem” :-D

Nie popadajmy w skrajności. Każdy z nas robi błędy i przyzwyczaja się do błędnych form, ale to miejsce służy chyba właśnie rozwiewaniu takich wątpliwości, żeby interfejs QGIS-a nie podążał na oślep za modnym ostatnio trendem bylejakościoizacji robienia wszystkiego. Więc proszę, chociaż tutaj nie nazywajmy błędów językowych drobiazgiem ;-)
