### ISSUE TITLE
Edytuj obiekty wewnętrznie

### ISSUE THREAD

**Issue by borysiasty** [Cracert/QGIS-trans-PL#103]
![zrzut_20181015_224425](https://user-images.githubusercontent.com/1000043/46977299-20620280-d0cc-11e8-979e-979ddad3645d.png)

Gdybym nie wiedział, o co chodzi, to za Chiny bym nie zgadł :-) W oryginale jest niewiele lepiej (*Edit Features In-Place*), ikonka też nie pomaga, więc proponuję pójść na całość i przetłumaczyć to pełnym zdaniem. Wprawdzie to nie jest formalnie tooltip, tylko nazwa q-akcji, która w przyszłości może pojawić się gdzie indziej (np. w menu), ale póki co akcja jest wyzwalana tylko z tego przycisku, więc nazwa pokazuje się tylko jako tooltip.

Proponuję coś takiego (z uwagą w nawiasie, żeby nikt się nie zdziwił, gdy po wciśnięciu zniknie 90% algorytmów). Szlif tego lub lepszy pomysł mile widziane.

**Edytuj źródłową warstwę, zamiast tworzyć nową (uwaga, tylko niektóre algorytmy obsługują ten tryb)**

**Comment by miszokienka** [comment]
Może `Edytuj w źródle`?

**Comment by borysiasty** [comment]
@miszokienka 
> Może Edytuj w źródle?

Hmmm, też bym się nie domyślił, o co chodzi :) Ale może tylko ja taki niedomyślny jestem.

**Comment by miszokienka** [comment]
A co powiecie na `Edytuj w warstwie źródłowej`?

**Comment by borysiasty** [comment]
Teraz bym zrozumiał :) Ale to moje pełne zdanie za długie, czy co? Uważasz, że nie ma sensu wyjaśniać, czemu 90% algorytmów zniknie po wciśnięciu tego?

**Comment by miszokienka** [comment]
Ojaa, Borys, przepraszam :) A tak byłem zadowolony, że mi wpadł pomysł do głowy :D
Ale przyznam, że krótsza forma mi bardziej pasuje, jestem zwolennikiem skracania. Chociaż Twoja wersja jest czytelniejsza.
Co do wytłumaczenia zniknięcia algorytmów to mam mieszane uczucia, ale jednak bym z tego zrezygnował ze względów krótkościowych.

**Comment by borysiasty** [comment]
Spoko spoko. Edytuj w warstwie źródłowej jest już ok.

**Comment by borysiasty** [comment]
Daję **Edytuj w warstwie źródłowej** i zamykam. Jak ktoś będzie miał lepszy pomysł, to niech poprawia.
