### ISSUE TITLE
Mój pierwszy raz

### ISSUE THREAD

**Issue by borysiasty** [Cracert/QGIS-trans-PL#104]
Ja wiem, że jestem stary i nie mam poczucia humoru, ale to trochę słabo wyszło...

![zrzut_20181019_204809](https://user-images.githubusercontent.com/1000043/47237805-755d8b80-d3e0-11e8-944e-a6ae7634d3d6.png)

Szczerze mówiąc, nie wiem, jak to sprytnie i na luzie sformułować. Może chociaż bez tego uśmieszku... ;p Co ciekawe wygląda na to, że ten wybór pojawia się nawet wtedy, gdy na kompie nie było nigdy QGIS-a 2. W oryginale jest w każdym razie:
```
Ready to go?
 *  Import settings from QGIS 2
 *  I want a clean start. Don't import my QGIS 2 settings. 
```

Btw. z całym szacunkiem dla różnorodności dialektycznej, proponowałbym jednak trzymać się obowiązującego w Polsce dialektu mazowieckiego i zrezygnować z przeglądnijania. Ale nie napinam się. Na ten pierwszy raz bardziej :p

**Comment by Cracert** [comment]
[W słowniku PWN](https://sjp.pwn.pl/slowniki/przegl%C4%85dnij.html) słowo `przeglądnij` jest równoprawne z `przejrzyj`. Dla mnie to drugie brzmi w tym kontekście dziwnie, ale rozumiem, że to ten sam problem, tylko widziany z innego regionu. Generalnie nie upieram się. A może zróbmy ankietę na forum, podając dwie wersje tego zdania? 

`Pierwszy raz` oczywiście jest do zmiany - śmiało modyfikujcie to.

**Comment by borysiasty** [comment]
Ej, ale chyba zdajesz sobie sprawę, że regionalizm ``przeglądnij`` wszędzie poza Małopolską (a może bardziej poza Galicją, tak dokładnie nie znam jego zasięgu), brzmi po prostu jednoznacznie krakowsko. Brzmi dokładnie tak samo regionalnie, jak *syćki* brzmi podhalańsko, a *jo* - w zależności od kontekstu - śląsko lub kaszubsko :) Tak, jak napisałem, nie upieram się, możemy być open i przemycać takie regionalne smaczki tu i ówdzie, tylko nie zrównujmy ich z formą ogólnopolską :)

**Comment by Cracert** [comment]
Szczerze mówiąc nie do końca zdaję sobie z tego sprawę, i nie było moim celem przemycanie regionalizmów. Ale widocznie jestem nimi przesiąknięty. 

Ciekaw jestem na ile odstaję od normy, stąd pomysł ankiety. Co nam szkodzi?

**Comment by borysiasty** [comment]
Mnie nic nie szkodzi, śmiało :)

**Comment by miszokienka** [comment]
Tak, okienko wyświetla się też np. po pierwszej instalacji na kompletnie nowym komputerze, który nigdy wcześniej QGISa nie widział.

Co do `Przeglądnij`, to dla mnie też brzmi dziwnie, chociaż mam w sobie pół krwi podkrakowskiej ;) Moje propozycje to `Przejrzyj`, `Przeglądaj` lub `Sprawdź`.

Z pierwszego razu wg mnie trzeba wyrzucić co najmniej uśmiech, a może nawet zmienić całość na bardziej poważną formę. W końcu QGIS to poważny program. Proponuję:

> Gotowy? 
> - importuj ustawienia z QGIS 2 (jeśli istnieją) 
> - _(tu jeszcze nie mam pomysłu, ale początek mi nie pasuje też)_

**Comment by borysiasty** [comment]
Wersja ``Gotowy?`` jest w porządku, chociaż jakaś taka na wpół wyrwana z kontekstu. Przydałoby się tu pełniejsze zdanie, tylko właśnie nie wiem, jakie :) Przypuszczam, że nawet i *pierwszy raz* by mnie rozweselił, gdyby był z wyczuciem zaszyty w dłuższym zdaniu, a tak nie bardzo wiadomo, o co cho :) 

W każdym razie w braku lepszego pomysłu daję łapę za wersją Misia. Zastrzeżenie w nawiasie jest fajne. W drugim punkcie może *Zacznijmy wszystko od nowa. Nie importuj niczego z QGIS 2* ;) 

No właśnie, trochę razi mnie to QGIS w dopełniaczu i we własnych tekstach na własną odpowiedzialność piszę zwykle *QGIS-a*, ale nie jestem pewien, czy ta forma jest poprawna. Zwłaszcza, że po rozwinięciu skrótu wychodzi *Systema* :) Przydałby się nam ktoś, kto mówi poprawnie po polsku... Niestety nie znam nikogo takiego osobiście :/

**Comment by borysiasty** [comment]
To na dziś mamy taką propozycję (i niecałe 40 godzin na zgłoszenie lepszej :) )

> Gotowy? 
> - importuj ustawienia z QGIS 2 (jeśli istnieją) 
> - zacznijmy wszystko od nowa -- nie importuj starych ustawień

**Comment by miszokienka** [comment]
Skoro mamy `Gotowy?`, to może na dole zrobić `Zaczynam!` zamiast `Zaczynamy!`, żeby było spójnie w tej samej osobie?
I co z `Przeglądnij`? Na czym stanęło? ;)

**Comment by borysiasty** [comment]
Jak dla mnie może być ``zaczynam`` (aczkolwiek tam było zacznijmy, a nie zaczynamy -- ot, tak lirycznie pojechałem ;p). Ważne, żeby wygrzebać z Worda albo skądś półpauzę i nie wstawiać minusa (tutaj używam dwóch, jak w LaTeXu, ale to się samo nie konwertuje niestety :) ).

Zrobiłem mały risercz. O ile dla mnie, jako osoby jakoś tam interesującej się językiem, ``przeglądnij`` jest  oczywistym regionalizmem, to ze zdziwieniem odkryłem, że wiele osób nigdy tej formy nie słyszało. Również niemłodych i wykształconych. Więc może tylko dla mnie to byłby taki smaczek, a dla większości użytkowników wyglądałoby dziwacznie. Zatem głosowałbym a formą ogólnopolską ``przejrzyj``.

**Comment by miszokienka** [comment]
Chodziło mi o `Zaczynamy!` na przycisku na dole okna.
Poprawione na `Zaczynam!` oraz na `zacznijmy wszystko od nowa – nie importuj starych ustawień`

**Comment by borysiasty** [comment]
Zmieniłem na formę ogólnopolską. Natomiast te dwie opcje rozpocząłem wielką literą, bo jak jest kropka, to jest zdanie -- nie ma bata :)
