### ISSUE TITLE
Datetime

### ISSUE THREAD

**Issue by miszokienka** [Cracert/QGIS-trans-PL#105]
Tłumaczyć typ `datetime `jako `data/czas`, czy zostawić jako `datetime`?

**Comment by borysiasty** [comment]
Ja bym spójnym był. Tam, gdzie jest ``liczba całkowita``, tam bym tłumaczył i to. Wszak różne typy danych zwykle sąsiadują ze sobą - czy to na listach rozwijalnych, czy w tabelkach. Zresztą chyba w wielu miejscach zostawiamy w nawiasie oryginał ``liczba całkowita (Integer)``.

**Comment by miszokienka** [comment]
Pytanie powstało podczas edycji opisów pojawiających się w oknie edytora wyrażeń. Na razie zrobiłem proste `data/czas` i dodam, że mogłem przeoczyć niektóre wystąpienia.

**Comment by borysiasty** [comment]
@miszokienka Czyli można zamykać?

**Comment by miszokienka** [comment]
Raczej tak, chociaż w tej chwili występują tam pewnie jakieś nieścisłości, bo nie wiem czy wszystko zrobiłem na jedno kopyto na pewno...

**Comment by borysiasty** [comment]
No to zamykam, bo to potem wisi dwa lata i nikt i tak nie zagląda.
