### ISSUE TITLE
Upiec ciasto dla Misia

### ISSUE THREAD

**Issue by borysiasty** [Cracert/QGIS-trans-PL#107]
Osiągnęliśmy oszałamiające rezultaty, przy czym *my* jest tu troszkę na wyrost:

- QGIS 3.2: ``73,6%``
 - QGIS 3.4: ``92,8%``

Jeden człowiek, dwie ręce, dwadzieścia pięć palców i 101 klawiszy. Kto na ochotnika idzie do sklepu?

 - [ ] 1 i 1/3 szklanki mąki pszennej (około 250 g)
 - [ ] 3/4 szklanki cukru
 - [ ] 2 szklanki startej marchewki
 - [ ] 2/3 szklanki stopionego masła
 - [ ] 2 szklanki posiekanych orzechów włoskich lub migdałów
 - [ ] 4 jajka
 - [ ] 1 szklanka jabłek; pokrojonych w drobną kostkę
 - [ ] 5 łyżek suszonej żurawiny
 - [ ] 50 ml rumu
 - [ ] 2 łyżeczki sody oczyszczonej
 - [ ] 1 i 1/2 łyżeczki proszku do pieczenia
 - [ ] 1 łyżeczka ekstraktu z wanilii
 - [ ] szczypta gałki muszkatołowej
 - [ ] szczypta soli
 - [ ] szczypta zmielonych goździków
 - [ ] szczypta cynamonu
 - [ ] skórka z jednej pomarańczy
 - [ ] Krem z białej czekolady i mascarpone:
 - [ ] 250 g serka mascarpone
 - [ ] 1 tabliczka białej czekolady
 - [ ] skórka ze świeżej pomarańczy

**Comment by miszokienka** [comment]
`dwadzieścia pięć palców` ?
Jak będę koło sklepu to załatwię tak z połowę tej listy ;)

**Comment by borysiasty** [comment]
Ty?

**Comment by alinager** [comment]
@miszokienka Czy w ramach tortu dziękczynnego można Cię publicznie ogłosić na fejsie QGISowym dobroczyńcą roku? :)

**Comment by miszokienka** [comment]
@alinager Nie pisz tylko, że mam 25 palców ;)

**Comment by borysiasty** [comment]
Może troszkę wirtualnie, ale upieczone.
