### ISSUE TITLE
Mesh

### ISSUE THREAD

**Issue by borysiasty** [Cracert/QGIS-trans-PL#108]
Jak się tłumaczy mesha?  Tutaj chyba światek hydro-meteo się najlepiej zna. Nie wiem, czy funkcjonuje wśród np. określenie *statka*, ale jeśli tak, to żeby się nie pomyliło z siatkami kartograficznymi. 

Teraz mamy np. **Dodaj warstwę mesh**, co jest bezpiecznym rozwiązaniem, ale pewnie niekoniecznie optymalnym...

**Comment by miszokienka** [comment]
Ja bym chyba zostawił mesh. To występuje pewnie w wielu innych
oprogramowaniach i mogłoby mylić użytkownika jeśli coś sobie wymyślimy. Ja
tego nie używałem nigdy, więc w sumie nie wiem, czy w ogóle istnieje jakieś
tłumaczenie rozsądne.

**Comment by borysiasty** [comment]
Zamykam, chyba już wszędzie jest przetłumaczone na Siatka.
