### ISSUE TITLE
Decimal places w Opcjach i Map Tools

### ISSUE THREAD

**Issue by erpas** [Cracert/QGIS-trans-PL#11]
_Decimal places_ tłumaczone jako _Cyfr dziesiętnych_.
Proponuję _ilość cyfr dzesiętnych_ lub  _ilość miejsc po przecinku_.

**Comment by Cracert** [comment]
:-1: 
Wiadomym jest, że chodzi o liczbę :).
A co powiecie na _cyfr po przecinku_?

**Comment by erpas** [comment]
+1 dla cyfr po przecinku
