### ISSUE TITLE
Różności z okna "Edytuj akcję" (kontekst QgsActionScopeRegistry)

### ISSUE THREAD

**Issue by borysiasty** [Cracert/QGIS-trans-PL#111]
![zrzut_20181204_175316](https://user-images.githubusercontent.com/1000043/49458689-9ee64100-f7ed-11e8-8003-20285af5f352.png)

**Comment by miszokienka** [comment]
- `Mapy` (Canvas) poprawiłem na `Widok mapy`
- `Wykonaj jeśli komunikat pasuje do` poprawiłem na `Wykonaj, jeśli komunikat pasuje do wzoru`
- `Możliwości akcji` (Action Scopes) poprawiłem na `Kontekst akcji`

Nie miałem pomysłu, co wpisać w `Available for the action map tool on the canvas.`, żeby nie zmylić użytkownika. Nie korzystam z tych opcji (jeszcze) ;)

**Comment by borysiasty** [comment]
Może ``Dostępne dla narzędzia akcji na mapie``? Chodzi o to, że akcję odpalamy klikając na mapie, a nie w tabeli atrybutów.

Btw. to narzędzie ma tooltip ``Uruchom działanie na obiekcie`` - trzeba by się zdecydować, czy to jest akcja, czy działanie. Chyba wszyscy mówią już *akcja*.

To jeszcze spacja w "Dla typuPython" :)

**Comment by borysiasty** [comment]
Poprawiłem "Dla typuPython", zamykam.
