### ISSUE TITLE
Mesh layers

### ISSUE THREAD

**Issue by borysiasty** [Cracert/QGIS-trans-PL#112]
Jakieś pomysły? :) Straszy ten mesh w głównym menu.

**Comment by erpas** [comment]
Proponuję zwyczajnie: `siatka`. Żeby odróżnić od siatki karto można, tam gdzie to konieczne, dodawać 'obliczeniowa'.  

mesh layer = warstwa siatkowa

mesh dataset = zbiór danych siatkowych

Przed momentem wprowadziłem to do transifeksa.

**Comment by borysiasty** [comment]
@erpas dzięki. Na marginesie: to tłumaczenie jest już przyjęte w świecie hydro/meteo, czy wchodzimy na dziewiczy ląd? W moich dziedzinach meshy się nie stosuje, więc nie wiem, czy i jak to ktoś już tłumaczył.

**Comment by miszokienka** [comment]
Rozmawiałem na ten temat z kilkoma osobami na spotkaniu w Poznaniu. Wg nich powinno po prostu pozostać **mesh**. Wg mnie też. Skoro jest problem z jasnym i intuicyjnym przetłumaczeniem tego, to nie robił bym tego na siłę.

**Comment by erpas** [comment]
@borysiasty w publikacjach naukowych spotykałem się z tłumaczeniem "siatka (obliczeniowa)".

@miszokienka rozumiem, że chodzi o odróżnienie od siatki karto (grid), tak? Czy o jaką inną niejasność i nieintuicyjność chodzi?

**Comment by borysiasty** [comment]
No to mamy remis. Będziecie walczyć w budyniu.

Dla mnie niejasność i nieintuicyjność pojedynczego słowa "Siatka" polega nawet nie tyle na myleniu, co na braku skojarzenia z typem danych ("Warstwa siatkowa" już lepiej naprowadza). Ale nie chcę zabierać głosu, wolałbym, żeby użytkownicy meshy ustalili jakiś termin i wprowadzili go we wszystkich programach :)

**Comment by erpas** [comment]
Obliczeniowcy mówią "mesz", ale gdy przychodzi do pisania po polsku, to używają niejednoznacznego "siatka". Niejednoznaczność dotyka głównie tych, którzy nie używają siatek do obliczeń, bo dla mnie w QGIS sprawa jest prosta: albo chodzi o grida albo siatkę obliczeniową. Spodziewam się, że jeśli QGIS uruchomiony jest przez obliczeniowca, to siatka będzie mu się kojarzyć w miarę jednoznacznie. Nie wiem, czy ujednoznaczniać to na siłę dla tych, którym bardziej kojarzy się to z torbą na zakupy i nie będą z tego korzystać.

Czy mamy jakieś inne nieprzetłumaczone określenie w polskim interfejsie?

**Comment by borysiasty** [comment]
Zamykam, chyba już wszędzie jest przetłumaczone na Siatka.
