### ISSUE TITLE
O rozmieszczaniu obiektów na wydrukach

### ISSUE THREAD

**Issue by erpas** [Cracert/QGIS-trans-PL#113]
W menu rozmieszczania obiektów na wydrukach pojawiły się nowe pozycje (zob. poniżej) i przy tej okazji chciałem Was prosić o odniesienie się do propozycji zmiany istniejących tłumaczeń rozmieszczeniowych.

![image](https://user-images.githubusercontent.com/3106699/69011564-3c3d7500-096c-11ea-8a09-f11468ed3222.png)

Mimo że "distribute", to w istocie chodzi tu o wyrównanie odległości pomiędzy określonymi częściami obiektów lub, co nowe, pomiędzy całymi obiektami. Poniżej zamieszczam tabelę z istniejącymi tłumaczeniami i propozycjami zmian. Proszę, dajcie znać, co myślicie.

Źródło | Obecne tłumaczenie | Propozycja 
--------| -----------------------| -------------
Distribute &Left Edges | Rozmieść wg &lewych krawędzi | Wyrównaj odległości lewych krawędzi
Distribute Horizontal &Centers | - | Wyrównaj poziome odległości centrów
Distribute &Horizontal Spacing Equally | - | Wyrównaj poziome odstępy
Distribute &Right Edges | Rozmieść wg &prawych krawędzi | Wyrównaj odległości prawych krawędzi
Distribute &Top Edges | Rozmieść wg &górnych krawędzi | Wyrównaj odległości górnych krawędzi
Distribute &Vertical Centers | Rozmieść wg &centrów (pionowych) | Wyrównaj pionowe odległości centrów
Distribute Vertical Spacing Equally | - | Wyrównaj pionowe odstępy
Distribute &Bottom Edges | Rozmieść wg &dolnych krawędzi | Wyrównaj odległości dolnych krawędzi

Z rozpędu wrzuciłem tłumaczenia dla nowych obiektów, ale potem pomyślałem, że warto skonsultować głębsze zmiany. Z góry dzięki za sugestie!

**Comment by borysiasty** [comment]
+1

**Comment by miszokienka** [comment]
Ja obiecuję sprawdzić jak te opcje działają w praktyce i się odnieść.

**Comment by Cracert** [comment]
Jak dla mnie te propozycje są bardzo dobre. Jedyne co bym zmienił to `centra` na `środki`, ale nie upieram się.

**Comment by borysiasty** [comment]
No tak, *środek* znacznie lepszy. Też mi te centra wpadły do oka, ale wymyśliłem tylko centroidy, więc machnąłem ręką.

**Comment by miszokienka** [comment]
Przychylam się do tego, co proponuje @Cracert. `Centra `brzmi trochę obco. `Środki` są ok i całe tłumaczenie też.

**Comment by erpas** [comment]
Dzięki za uwagi! Zamieniam `centra` na `środki` i wrzucam propozycje na Transifex.
