### ISSUE TITLE
Zmiana symbolu legendy (Patch)

### ISSUE THREAD

**Issue by gsienkoPL** [Cracert/QGIS-trans-PL#115]
W 3.14 pojawia się wiele ulepszeń legendy, między innymi możliwość zmiany symbolu czy wygląda poszczególnych elementów legendy.  

Patch - propozycja, dość literalnie, Łatka 

Jakieś porównanie do ArcGISa?

**Comment by Cracert** [comment]
`Łata` jest chyba ogólnie zrozumiała, ale nie zdrabniałbym.

**Comment by borysiasty** [comment]
Dla mnie łata wcale nie jest taka zrozumiała, chociaż nie wiem, jak jest przyjęte w innych programach. Łatka jakby bardziej intuicyjna, a jeszcze bardziej jakaś "próbka", "wzornik", jeśli już iść w tekstylne skojarzenia. Ale to nadal nie jest dobre. Najchętniej użyłbym tutaj słowa "kształt", zaś shape przetłumaczył na coś bardziej szczegółowego... Tylko nadal nie wiem... WKT? Definicja? Obrys?

**Comment by gsienkoPL** [comment]
Ten `patch` to poligon, punkt lub linia, dodatkowo można jeszcze zedytować symbol. `patch` ma też swoje miejsce w stylach, można je sobie importować i eksportować. Przetłumaczę wszystkie linie związane z tym tematem, zobaczę jak to będzie wyglądać i wrzucę propozycje.

**Comment by borysiasty** [comment]
No to po kolei:

Legenda składa się z `elementów` (aka `obiektów` we frazie *Właściwości obiektu legendy*, którą jednak bym uspójnił do elementu).

Dalej widzę dwa podejścia:

1. Uznanie, że `Element` legendy składa się z dwóch **podelementów**: `patcha` i `etykiety`, 
   czyli `Patch` to pełnoprawny element o czterech atrybutach: `shape`, `width`, `height` i `symbol`, który go wypełnia. 
   
   Wtedy `shape` to *kształt* tego patcha, któremu trzeba wymyślić tłumaczenie. Takiej interpretacji przeczy fakt, że sekcja `Custom symbol` nie jest częścią sekcji `Patch`, a jest na równi z nią.

   
2. Uznanie, że `Element` legendy ma trzy **atrybuty**: `patch`, `symbol` i `etykietę`.
   zaś atrybut `Patch` ma trzy składowe: `shape`, `width`, `height`.
   
   W takim wypadku `patch` jest *kształtem elementu legendy*, a pozostaje problem tłumaczenia `shape`. Z kolei w bibliotece stylów `Legend patch shape` można przetłumaczyć na `Kształt elementu legendy`.
   
    Słabość tej interpretacji pojawia się przy elementach punktowych (choć tutaj cały `patch` jest na siłę i może powinien zostać wyłączony). Przy punktach `shape` można użyć do zastąpienia punktu miultipunktem (i tylko tyle) zaś `width` i `height` do rozciągnięcia całego `patcha`, czyli zwiększenia marginesów `symbolu`. 

Sam nie wiem, która jest gorsza :)

**Comment by gsienkoPL** [comment]
Dla mnie opcja nr 2.

**Comment by miszokienka** [comment]
Gdzie znaleźć tą nowość? Szukam w wersji dev i nie wiem o czym tu mowa ;)

**Comment by gsienkoPL** [comment]
Dla wyłączonej aktualizacji legendy dwuklik na symbol.

**Comment by borysiasty** [comment]
Dla leniwych: Elementowi legendy możemy teraz przypisać kształt i wymary/proporcje (poniżej w Custom Symbol widać, że nadpisałem też standardowy symbol dla tej linii niebieską kreską - to jest zupełnie niezależne do pacza):
![patch](https://user-images.githubusercontent.com/1000043/82082741-d6e2fa80-96e8-11ea-8e48-55edb5d0bfc0.png)

Po kliknięciu w ten długi klawisz szejpu pacza pojawia się edytorek WKT z możliwością zapisu do biblioteki (zapisuje się sam nieskalowany szejp bez wymiarów/proporcji):

![patch definition](https://user-images.githubusercontent.com/1000043/82083125-799b7900-96e9-11ea-8adb-e8724fdde4f7.png)

**Comment by gsienkoPL** [comment]
Jest już dostępna coś ala, biblioteka do zaimportowania: [repozytorium na githubie](https://github.com/kartoza/QGIS-Legend-Patches). Ludzie już zaczęli tworzyć różne kształty.

Ja powiem tak, dla mnie, dla mojej firmy, to opcja must have, aby mieć pełną kontrolę nad symbolami legendy.

Zastosowanie. Np QGIS ma problem z wyświetleniem symbolu gdzie jest użyte jako jednostka m, nie wspominając o różnych opcjach związanych z generatorem geometrii. Edycja symbolu w legedzie, Bomba.

**Comment by miszokienka** [comment]
A ta opcja dotyczy (będzie dotyczyć) również legendy dla QGIS Servera?
Jak dla mnie tutejszy `Patch` najbardziej obrazowo brzmi jako `Nakładka`

**Comment by gsienkoPL** [comment]
Nie znalazłem takiej informacji. Można jakoś się dobrać do dev wersji serwera?

**Comment by borysiasty** [comment]
> Jest już dostępna coś ala, biblioteka do zaimportowania: repozytorium na githubie. Ludzie już
> zaczęli tworzyć różne kształty.

Super! To teraz czekamy, aż się pojawi w Resource Sharingu :)

> A ta opcja dotyczy (będzie dotyczyć) również legendy dla QGIS Servera?

W GetPrint zapewne tak, a co do GetLegendGraphics, to szczerze mówiąc nigdy się nie zastanawiałem, czy to przechodzi przez system legendy wydrukowej, czy po prostu leci to samo, co do panelu warstw.

> Jak dla mnie tutejszy Patch najbardziej obrazowo brzmi jako Nakładka

Ale nakładka musi być na coś, a ta *próbka symbolu w legendzie* nijak nie kojarzy mi się z nakładaniem. Już bardziej nadpisanie symbolu jest nakładką.

> Nie znalazłem takiej informacji. Można jakoś się dobrać do dev wersji serwera?

Nie trzeba się dobierać, wystarczy zainstalować ;) Metoda zależy od systemu operacyjnego. Jeśli masz Windowsy, to pewnie jest w OSGeo4W? Jak nie ma, to trzeba skompilować.

**Comment by gsienkoPL** [comment]
Poczynione.
![00-46-24](https://user-images.githubusercontent.com/16090543/82957729-04b32380-9fb4-11ea-8f55-b656b47dca51.png)

![00-46-52](https://user-images.githubusercontent.com/16090543/82957733-0846aa80-9fb4-11ea-8138-1a6b924d17d1.png)

![00-47-58](https://user-images.githubusercontent.com/16090543/82957737-0aa90480-9fb4-11ea-9443-3d89c138a727.png)

**Comment by borysiasty** [comment]
@gsienkoPL Czy to już jest do zamknięcia?

**Comment by borysiasty** [comment]
@gsienkoPL Z rozpędu zamknąłem ;) W razie czego otwórz proszę.
