### ISSUE TITLE
Odwrócona kolejność: "Wyświetl symbol warstwy" zamiast "Wyświetl warstwę symbolu"

### ISSUE THREAD

**Issue by borysiasty** [Cracert/QGIS-trans-PL#116]
![Zrzut_20200515_123319](https://user-images.githubusercontent.com/1000043/82041358-51d7f100-96a8-11ea-8f7e-5ecf6f603831.png)

**Comment by borysiasty** [comment]
Chyba, że to było intencjonalne, ale wtedy powinno być *Wyświetl symbol warstwy symbolu* :)

**Comment by borysiasty** [comment]
@gsienkoPL widzę, że to Twoje, to nie będę poprawiać w buciorach ;)

Btw. a może zamiast `Wyświetl` raczej `Wyświetlaj` albo `Włącz warstwę symbolu`? Luźne myśli.

**Comment by gsienkoPL** [comment]
To było intencjonalne. A może lepiej samo `Wyświetlaj symbol`. Bez wchodzenia już w dalsze szczegóły.

**Comment by borysiasty** [comment]
No ale przecież on nie steruje wyświetlaniem całego symbolu, tylko jednej z jego warstw. 

Chyba, że masz symbol jednowarstwowy, to siłą rzeczy zniknie cały, ale wtedy nie ma sensu używania tego przełącznika.

**Comment by gsienkoPL** [comment]
Tylko że on pojawia się w kontekście konkretnego elementu symbolu, gdzie wyświetlaniem tego element można sterować nie zależnie  od jego zagłębienia w drzewku stylu.  Po dyskusji bym był za tym aby skrócić właśnie do `Wyświetlaj symbol`. IMHO będzie OK.

Jak jest przyjęty zwyczaj (ja nowy przy tłumaczeniu.. ) przy różnicy zdań co do tłumaczenia? :)

**Comment by miszokienka** [comment]
Ja jestem zdecydowanie za najbardziej intuicyjnym tłumaczeniem tego, czyli `Wyświetlaj warstwę symbolu`. Ewentualnie zamiast `warstwę` można dać `element` lub `część`, ale to już mniej intuicyjne.
`Wyświetlaj symbol` jest dość mylące, bo sugeruje, że chodzi o wyświetlanie całego symbolu obiektu, a tymczasem, jak wspomniał Borys, sterujemy tu tylko pewnym fragmentem całego symbolu.

P.S. Ostatnio sam się złapałem, że korzystając z programu nie wiedziałem co właściwie ten przełącznik robi, byłem pewny że wyłącza cały symbol obiektu.

**Comment by borysiasty** [comment]
> Tylko że on pojawia się w kontekście konkretnego elementu symbolu, gdzie wyświetlaniem tego 
> elementu można sterować niezależnie od jego zagłębienia w drzewku stylu.

Ta cała terminologia jest tak zagmatwana, że staram się precyzyjnie trzymać angielskich odpowiedników, co jest stylem, co symbolem, co warstwą itp. Dlatego `stylu` w to nie mieszajmy, on opisuje sposób użycia symboli do wizualizacji warstwy mapy. 

Korzeniem tego drzewka jest `symbol`, a gałęziami pierwszego poziomu są jego `warstwy`. Warstwa symbolu może być np. *znacznikiem z wypełnienia*, który z kolei składa się z zagnieżdżonego `symbolu`, a ten może mieć kolejne `warstwy` itd. Zauważ, że ten przełącznik nie występuje na poziomach poszczególnych symboli, zaś jedynie na poziomach ich warstw. Zatem nie możesz nim wyłączyć żadnego z symboli (ani głównego, ani zagnieżdżonego), natomiast możesz nim wyłączyć dowolną warstwę dowolnego z tych symboli. W związku z powyższym, określenie *Wyświetlaj symbol* byłoby dokładnie przeciwne do stanu faktycznego.

> Jak jest przyjęty zwyczaj (ja nowy przy tłumaczeniu.. ) przy różnicy zdań co do tłumaczenia? :)

Upartszy zwycięża :)
https://xkcd.com/386/

**Comment by gsienkoPL** [comment]
> Upartszy zwycięża :)

hehe, OK.

Dobra, macie rację. Czyli `Wyświetlaj warstwę symbolu`.  +1.

**Comment by gsienkoPL** [comment]
Zmienione.
![00-32-31](https://user-images.githubusercontent.com/16090543/82957109-928e0f00-9fb2-11ea-8861-42dc6a99f66d.png)
