### ISSUE TITLE
Vector tile

### ISSUE THREAD

**Issue by gsienkoPL** [Cracert/QGIS-trans-PL#117]
Nowe źródło danych - znajdziemy w opcjach, w zarządzaniu źródłami, processingu itp.

ArcGIS. - **Warstwa kafli wektorowych.** [źródło](https://enterprise.arcgis.com/pl/portal/10.5/use/vector-tile-layers.htm).

Zostawiamy zgodnie z ArcGISem - **Kafle wektorowe** jako bazowy termin?

**Comment by borysiasty** [comment]
Ja tak je nazywam. Termin prosty, dobrze oddający istotę i łatwo kojarzący się z oryginałem, więc +1.

**Comment by gsienkoPL** [comment]
To idąc za ciosem. Warstwa xyz jako `kafle rastrowe`? Byśmy ujednolicili.

**Comment by borysiasty** [comment]
Hmm...

Kłopot w tym, że XYZ jest tylko jednym z obsługiwanych przez QGIS-a standardów kafli rastrowych. Drugi jest tuż obok (WMTS), a trzeci (TMS) dostępny poprzez warstwę wirtualną. Nie wiem, czy również ArcGisMapServer nie udostępnia kafli.

Tłumaczenie `kafle rastrowe` kusi zwartością, ale gubi informację, że tutaj należy szukać wyłącznie XYZ-ów. Wobec sąsiedztwa z `WMTS`-em wygląda wręcz dezorientująco. Oczywiście XYZ jest najpopularniejszy, ale tłumaczenie nie powinno wprowadzać w błąd. Zresztą nie myślę tu tylko o power userach, ale też np. o całej administracji, która *formalnie* na XYZ nie powinna nawet patrzeć, tylko używać PUWG-92 za pośrednictwem jednego z pozostałych protokołów.

Więc może `Kafle rastrowe XYZ`? Niewiele dłużej, a precyzyjnie. Co ciekawe te wektorowe też są XYZ, ale nigdy nie słyszałem, żeby ktoś je tak nazywał ;)

**Comment by borysiasty** [comment]
To chyba już się rozwiązało (inna sprawa, że w Przeglądarce są w wersji nieprzetłumaczalnej)
