### ISSUE TITLE
W którym pliku należy teraz tłumaczyć?

### ISSUE THREAD

**Issue by miszokienka** [Cracert/QGIS-trans-PL#118]
Od pewnego czasu (przegapiłem moment zmiany) w Transifeksie widać taki podział: 
![image](https://user-images.githubusercontent.com/26738097/89149845-b1ce8d00-d55d-11ea-88b1-1f287e265a12.png)
Prośba do osób bardziej zorientowanych o info, w którym pliku najlepiej tłumaczyć? W `qgis-application`, czy w `release-3-14--qgis-application`? Zdołałem zauważyć, że (przynajmniej niektóre) tłumaczenia przenoszą się na pozostałe pliki, ale nie uchwyciłem zasady... Chciałem dorzucić znów swoje kilka groszy do tłumaczenia i jestem zdezorientowany.

**Comment by borysiasty** [comment]
Też się pogubiłem, czy są jakieś backporty. Jeśli tak, to pewnie z `qgis-application` (czyli mastera) do 3.14, a nie odwrotnie. Chociaż kto wie. A może w ogóle nie ma, tylko po prostu zauważyłeś, że nowopowstałe pliki (ostatnio 3.14) są kopiowane z mastera? Ale może faktycznie coś przenoszą.

Ja ostatnio wklepywałem zmiany od razu w trzy miejsca (master, 3.14 i 3.10)

**Comment by miszokienka** [comment]
Trochę dziś dodałem od siebie. Zauważyłem, że chyba najlepiej tłumaczyć w 
`qgis-application`, bo z niego raczej się automatycznie przenoszą teksty do pozostałych plików. Czyli tak, jak piszesz Borys. Przy okazji zrobiłem małe porządki i wrzuciłem do tego pliku tłumaczenia, które były zrobione w 3.14, a brakowało ich w głównym pliku.
Jutro być może jeszcze trochę potłumaczę i poobserwuję czy i jak się propagują tłumaczenia między plikami.

**Comment by borysiasty** [comment]
Sprawa chyba już wyjaśniona :)
