### ISSUE TITLE
Zabrali nam ą

### ISSUE THREAD

**Issue by borysiasty** [Cracert/QGIS-trans-PL#119]
Na szczęście tylko z Windowsów.

W Q 3.14 zmieniono skrót akcji *Zlikwiduj zaznaczenie obiektów ze wszystkich warstw* z `Ctrl-Shift-A` na `Ctrl-Alt-A`, zaś stary dostała nowa akcja *Odznacz obiekty z bieżącej (aktywnej) warstwy*. Problem w tym, że Windowsy mapują Ctrl-Alt na AltGr (prawy Alt) i wszędzie tam, gdzie aktywne są akcje z głównego okna (np. w Lokatorze), przestało działać "ą".

Można zmienić skrót w naszym tłumaczeniu albo lobbować za globalną zmianą (AltGr-A chyba jest jeszcze używane w tureckim i łotewskim). Prosz o propozycje nowego skrótu. Można też odkręcić tę zmianę i przywrócić `Ctrl-Shift-A` starej akcji, a nową zostawić bez skrótu. 

Btw. żeby nie było za łatwo, przemianowałem właśnie w Transifeksie *Zlikwiduj zaznaczenie obiektów ze wszystkich warstw* na *Odznacz obiekty ze wszystkich warstw* (aby uspójnić z nową akcją).

**Comment by alinager** [comment]
To jeszcze nic. Zainstalowałam sobie ostatnio na komputerze taką aplikację co nazywa się Loom i służy do tworzenia filmów i nagrywania ekranu. Chwilę mi zajęło, zanim zorientowałam, że to ta apka zabrała mi literkę ć. Zamiast tego cały ekran zasypywało mi konfetti, niezależnie od tego, czy pisałam coś w przeglądarce, wordzie czy notatniku :D (przepraszam za off-topic)

**Comment by Cracert** [comment]
Dzięki @borysiasty za czujność! 

Osobiście zdaję się na Twoją opinię, bo nie mam w tej chwili jak tego sprawdzić i zaproponować coś sensownego. 

Jeśli możemy przemapować to sami - Ty jako developer albo z poziomu tłumaczeń - zrobiłbym to. Czyli pozostawiłbym nową akcję bez skrótu, a starej przywrócił poprzedni skrót. Kluczowa jest możliwość użycia polskich liter w wyszukiwaniu i raczej konserwatywne podejście do zmian. Ludzie przyzwyczajają się do skrótów.

**Comment by borysiasty** [comment]
Po przemyśleniu skłaniam się jednak do pozostawienia starego Ctrl+Shift+A w nowym znaczeniu (bieżącej warstwy), bo jest spójniej i bezpieczniej.

Ciąg dalszy sprawy: https://github.com/qgis/QGIS/pull/38608
Jeśli do najbliższego wydania (niecały tydzień) nie zmienimy u źródła, to usunę z naszego tłumaczenia.

**Comment by borysiasty** [comment]
Na razie przetłumaczyłem na Ctrl+Alt+W, bo nie mam pojęcia, jak zmusić Transifeksa do przetłumaczenia na pusty ciąg (zamiast uznania za nieprzetłumaczone).
