### ISSUE TITLE
Suppress attributes pop-up windows

### ISSUE THREAD

**Issue by erpas** [Cracert/QGIS-trans-PL#12]
Opcje > Digitalizacja > Suppress attributes pop-up windows after each created feature

jest 

_Zamknij formularz po stworzeniu obiektu_

proponuję:

_Nie pokazuj okna z atrybutami po utworzeniu obiektu_

**Comment by Cracert** [comment]
:+1: 
Słuszna uwaga i zmiana konieczna.

_Nie pytaj o atrybuty po utworzeniu obiektu_?

**Comment by erpas** [comment]
_Nie pytaj o atrybuty po utworzeniu obiektu?_

+1
