### ISSUE TITLE
Reuse last entered attribute values

### ISSUE THREAD

**Issue by erpas** [Cracert/QGIS-trans-PL#13]
Opcje > Digitalizacja > Reuse last entered attribute values

jest:

_użyj OSTATNIEJ wprowadzonej wartości_

proponuję:

_użyj OSTATNICH wprowadzonYCH wartości atrybutów_

**Comment by Cracert** [comment]
:+1: 
Delikatnie zmodyfikowałem (jak poniżej).
W razie czego otwórzcie ponownie temat.

_Użyj ostatnio wprowadzonych wartości atrybutów_
