### ISSUE TITLE
memory layer / temporary file

### ISSUE THREAD

**Issue by Cracert** [Cracert/QGIS-trans-PL#15]
_Memory layer_ tłumaczyliśmy dotychczas jako _warstwa tymczasowa_, bo nic z _pamięć_ nam nie pasowało. 
Ale ostatnio pojawiło się _temporary file_. 

Czy Waszym zdaniem możemy zostawić tak jak jest i tłumaczyć je odpowiednio:
_warstwa tymczasowa / plik tymczasowy_?
Ja myślę, że możemy tak zostawić.

**Comment by erpas** [comment]
Ja skłonny jestem używać 'warstwa w pamięci', ale jeśli Wam to nie pasuje,
to +1 dla warstwy i pliku tymczasowego.

W dniu 27 maja 2014 18:19 użytkownik Robert Szczepanek <
notifications@github.com> napisał:

> _Memory layer_ tłumaczyliśmy dotychczas jako _warstwa tymczasowa_, bo nic
> z _pamięć_ nam nie pasowało.
> Ale ostatnio pojawiło się _temporary file_.
> 
> Czy Waszym zdaniem możemy zostawić tak jak jest i tłumaczyć je odpowiednio:
> _warstwa tymczasowa / plik tymczasowy_?
> Ja myślę, że możemy tak zostawić.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Cracert/QGIS-trans-PL/issues/15
> .

## 

Używam wolnego oprogramowania:
https://www.gnu.org/philosophy/philosophy.pl.html

**Comment by Cracert** [comment]
Zmiana
