### ISSUE TITLE
enumeration

### ISSUE THREAD

**Issue by Cracert** [Cracert/QGIS-trans-PL#16]
_enumeracja_ czy _wyliczenie_?

Mamy teraz obydwa.

**Comment by erpas** [comment]
Czy chodzi o NUMEROWANIE obiektów czy jakiś inny proces?

W dniu 27 maja 2014 18:29 użytkownik Robert Szczepanek <
notifications@github.com> napisał:

> _enumeracja_ czy _wyliczenie_?
> 
> Mamy teraz obydwa.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Cracert/QGIS-trans-PL/issues/16
> .

## 

Używam wolnego oprogramowania:
https://www.gnu.org/philosophy/philosophy.pl.html

**Comment by Cracert** [comment]
Występuje w kontekście różnych typów widżetów (QgisApp). 
Na wiki odpowiednikiem jest chyba **lista** (http://pl.wikipedia.org/wiki/Wid%C5%BCet#Przyk.C5.82adowe_wid.C5.BCety)
Okazało się, że _enumeracja_ jest w starych/nieaktywnych tłumaczeniach.

_Wylicznie_ brzmi po ludzku, bo _enumeracja_ (choć poprawna) jest trudno zrozumiała.
_Lista_ jest najprostsza ze wszystkich.

**Comment by erpas** [comment]
+1 LISTA

W dniu 27 maja 2014 22:36 użytkownik Robert Szczepanek <
notifications@github.com> napisał:

> Występuje w kontekście różnych typów widżetów (QgisApp).
> Na wiki odpowiednikiem jest chyba _lista_ (
> http://pl.wikipedia.org/wiki/Wid%C5%BCet#Przyk.C5.82adowe_wid.C5.BCety)
> Okazało się, że _enumeracja_ jest w starych/nieaktywnych tłumaczeniach.
> 
> _Wylicznie_ brzmi po ludzku, bo _enumeracja_ (choć poprawna) jest trudno
> zrozumiała.
> _Lista_ jest najprostsza ze wszystkich.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Cracert/QGIS-trans-PL/issues/16#issuecomment-44331852
> .

## 

Używam wolnego oprogramowania:
https://www.gnu.org/philosophy/philosophy.pl.html
