### ISSUE TITLE
text edit

### ISSUE THREAD

**Issue by Cracert** [Cracert/QGIS-trans-PL#17]
_pole tekstowe_ czy _pole edycji_?

Mamy obydwa.

**Comment by erpas** [comment]
Nie każde pole tekstowe jest do edycji. Jeśli wiadomo, że dane pole
tekstowe jest miejscem do wpisania czegoś, to można je nazwać polem edycji,
ale skłaniam się do tego, żeby pozostawić je polem tekstowym.

2014-05-27 18:30 GMT+02:00 Robert Szczepanek notifications@github.com:

> _pole tekstowe_ czy _pole edycji_?
> 
> Mamy obydwa.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Cracert/QGIS-trans-PL/issues/17
> .

## 

Używam wolnego oprogramowania:
https://www.gnu.org/philosophy/philosophy.pl.html

**Comment by Cracert** [comment]
@borysiasty 

Zmieniłem jedyne wystąpienie **pole tekstowe** na **pole edycji**:
./src/gui/editorwidgets/core/qgseditorwidgetregistry.cpp:45
