### ISSUE TITLE
Tryb wyboru obiektów dla narzędzia informacji o obiekcie

### ISSUE THREAD

**Issue by erpas** [Cracert/QGIS-trans-PL#19]
Ostatnio dodany tryb, który pojawił się w wersji 2.2 to 'Layer selection'.
Proponuję zamienić obecne tłumaczenie: 
'Wybór warstwy' 
na 
'Zaznaczone warstwy'.

**Comment by Cracert** [comment]
Dzięki, zmiana wprowadzona.
