### ISSUE TITLE
Layer visibility presets

### ISSUE THREAD

**Issue by borysiasty** [Cracert/QGIS-trans-PL#20]
Mamy teraz nad listą warstw nowy toolbarek, a w nim klawisz "Manage Layer Visibility" (przetłumaczyłem na "Widoczność warstw"). W nim jest sekcja "Visibility Presets", którą przetłumaczyłem po prostu na "Zestawy" (Dodaj zestaw, nazwa dla nowego zestawu, usuń bieżący zestaw). Dla mnie to jest raczej "temat", ale powiedziano mi, że to nie jest zrozumiałe, więc został zestaw. Ktoś ma lepszy pomysł? Jeśli nie, to możemy zamknąć to issue.

**Comment by Cracert** [comment]
Nie ma tego już w tekście więc zamykam.
