### ISSUE TITLE
Siatki i mapy poglądowe

### ISSUE THREAD

**Issue by merkato** [Cracert/QGIS-trans-PL#21]
W composerze wydruków od wersji 2.8 pojawił się w błąd w tłumaczeniach dwóch pozycji.

We Właściwościach obiektu dla mapy, dotychczasowa zakładka Siatki została przetłumaczona jako "Warstwy Rastrowe". Kolejna zakładka powinna być przetłumaczona raczej jako Mapy poglądowe, a nie "Poglądy"
![a1_042](https://cloud.githubusercontent.com/assets/847295/7026783/153c4860-dd4c-11e4-8db1-baabc7ce2047.png)
![a1_043](https://cloud.githubusercontent.com/assets/847295/7026782/15391654-dd4c-11e4-9051-a13a1d6b0444.png)

**Comment by Cracert** [comment]
Dzięki @merkato za bardzo szczegółowo podane uwagi. Oczywiście masz rację z tymi tłumaczeniami. Poprawki będą dostępne od nadchodzącej wersji 2.10.

Zmiana jest tylko jedna. Skoro mamy Podgląd1, Podgląd2, ..., zamiast proponowanego **Mapy poglądowe** daliśmy **Mapy podglądu**.
