### ISSUE TITLE
Geoprocesing w menu Raster

### ISSUE THREAD

**Issue by erpas** [Cracert/QGIS-trans-PL#22]
Mam propozycję, aby zamienić Geoprocesing (org. Extraction) w menu tekstowym Raster na Wyodrębnianie.
Ta pozycja zawiera:
- warstwice
- kadrowanie

**Comment by Cracert** [comment]
Na pewno brzmi tutaj lepiej niż geoprocesing, ale kojarzy mi się z resekcją (zęba) :E

A co powiecie na **Cięcie**

**Comment by erpas** [comment]
O tak, cięcie jest jeszcze lepsze!

W dniu 22 czerwca 2015 22:50 użytkownik Robert Szczepanek <
notifications@github.com> napisał:

> Na pewno brzmi tutaj lepiej niż geoprocesing, ale kojarzy mi się z
> resekcją (zęba) :E
> 
> A co powiecie na _Cięcie_
