### ISSUE TITLE
topologia: dangle i pseudos

### ISSUE THREAD

**Issue by erpas** [Cracert/QGIS-trans-PL#23]
dajcie proszę znać, co myślicie o:
**dangle**: wiszący węzeł
**pseudo**: pseudokoniec

Oba terminy opisane:
http://docs.qgis.org/2.8/en/docs/user_manual/plugins/plugins_topology_checker.html

**Comment by Cracert** [comment]
**dangle**: węzeł wiszący

drugie jest OK - nic lepszego nie przychodzi i do głowy
