### ISSUE TITLE
Literówka w menedżerze

### ISSUE THREAD

**Issue by borysiasty** [Cracert/QGIS-trans-PL#24]
Plugin Manager: ReOzytoria wtyczek -> Repozytoria wtyczek

Czy to jest właściwe miejsce do zgłaszania błędów w tłumaczeniu? Żeby potem ktoś mógł je w jednej sesji poprawić. Kiedyś poprawiałem od ręki, ale Transifex mnie przerasta. Btw. potrzeba nam jakieś prostej procedury, jak obchodzić Transifexa i tłumaczyć ręcznie w pliku ts lub w Linguiście.

**Comment by erpas** [comment]
Poprawione. Dzięki za sygnał! Tak się umawialiśmy, że tutaj wrzucamy własne
uwagi i wątpliwości co do tłumaczenia.
Reszta świata może korzystać z powiadomień transifeksa, ale nie zdarza się
to zbyt często.

Do tłumaczenia w ligwiście można pobrać plik ts z:
https://www.transifex.com/projects/p/QGIS/resource/qgis-application/l/pl/download/for_translation/
tylko wtedy trzeba się dogadać z innymi tłumaczami, że się bierze całość na
własność i oddać możliwie szybko, żeby nie blokować innych.
Mówimy tu oczywiście o gorących okresach przed wydaniem kolejnej wersji, bo
normalnie tłoku w tłumaczeniu aplikacji nie ma :-)

W dniu 7 lipca 2015 10:22 użytkownik Borys Jurgiel <notifications@github.com

> napisał:
> 
> Plugin Manager: ReOzytoria wtyczek -> Repozytoria wtyczek
> 
> Czy to jest właściwe miejsce do zgłaszania błędów w tłumaczeniu? Żeby
> potem ktoś mógł je w jednej sesji poprawić. Kiedyś poprawiałem od ręki, ale
> Transifex mnie przerasta. Btw. potrzeba nam jakieś prostej procedury, jak
> obchodzić Transifexa i tłumaczyć ręcznie w pliku ts lub w Linguiście.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Cracert/QGIS-trans-PL/issues/24.

## 

Używam wolnego oprogramowania:
https://www.gnu.org/philosophy/philosophy.pl.html

**Comment by borysiasty** [comment]
@erpas (CC @Cracert):

> Poprawione. Dzięki za sygnał! Tak się umawialiśmy, że tutaj wrzucamy własne
> uwagi i wątpliwości co do tłumaczenia.

To wiem, tylko czy takie konkretne literówki można, czy zaśmiecam :)   

> Do tłumaczenia w ligwiście można pobrać plik ts z: ...

Tylko trzeba mieć konto na Transifeksie. A czym to się różni od użycia pliku ts z QGIS-owego kodu? Chodzi mi o: https://github.com/qgis/QGIS/tree/master/i18n 
Poza tym do poważniejszej pracy i tak plik ts trzeba sobie samemu wygenerować z lupdate, bo te  istniejące są odchudzone (mają powycinane lokalizacje napisów) i tłumaczy się po omacku. Po edycji mogę wygenerować również wersję odchudzoną, tylko pytanie, jak ją wrzucić potem z powrotem do transifexa? 

Idealnie byłoby tak: pobieram plik z kodu QGIS-a, edytuję, wrzucam do QGIS-a, a jakiś mądry skrypt aktualizuje transifexa na podstwie aktualnego QGIS-a. Podobno tak się nie da, tylko nie bardzo wiem, co stoi na przeszkodzie.

> tylko wtedy trzeba się dogadać z innymi tłumaczami, że się bierze całość na
> własność i oddać możliwie szybko, żeby nie blokować innych.

No chyba, że się właśnie bazuje na QGISowych plikach, bo potem można łatwo scalać różne wersje.

**Comment by Cracert** [comment]
Wrzucamy tutaj wszystko co znajdziemy, żeby później nam nie umknęło. Rozmiar nie ma znaczenia :)

Z ts-ami pracowałbym na bazie tych wersji z Transifexa, tak jak zaleca Werner. Pewnie ma ku temu jakieś powody. Czyli jeśli chcemy coś więcej i dokładniej przetłumaczyć pobieramy ts z Transifexa i później go wgrywamy z powrotem. 

Wystarczy jeden e-mail do nas albo tutaj na githuba - pobierzemy i wgramy do Transa.

**Comment by borysiasty** [comment]
Pogadam z Wernerem, bo to jakaś straszna kombinacja i nie chce mi się wierzyć, że nie da się prościej. A co do więcej i dokładniej, to jak mówiłem, nie wyobrażam sobie pracy na seryjnych ts-ach bez źródeł. Tymczasem się nie dotykam i będę tu podrzucał, dzięki :)
