### ISSUE TITLE
Wydruk -> właściwości mapy -> Warstwy rastrowe [wielki błąd]

### ISSUE THREAD

**Issue by borysiasty** [Cracert/QGIS-trans-PL#25]
W kompozytorze wydruku, we właściwościach obiektu Mapa, sekcja z siatkami nazwana jest "Warstwy rastrowe". Powinno być: "Siatki".

**Comment by Cracert** [comment]
Zostało to już zmienione w Transifexie. Nie widzisz tego w najnowszych kompilacjach? Nie pamiętam jaki jest tryb/częstotiliwość aktualizacji.
