### ISSUE TITLE
DB Manager -> Import vec layer -> Update options

### ISSUE THREAD

**Issue by borysiasty** [Cracert/QGIS-trans-PL#28]
Klawisz "Update options" wypełnia pola propozycjami wziętymi ze źródłowej warstwy. Z tego, co widzę, to pole "Table" nazwą szejpa, również pola z CRS-ami, czasem wyszarza pole Twórz obiekty elementarne (zapewne jeśli źródłowe takie są) - jak na załączonym obrazku. W polskim tłumaczeniu jest teraz bez sensu  "**_Opcje**_". 

![tlumacz](https://cloud.githubusercontent.com/assets/1000043/14204228/0c0e5c24-f803-11e5-986c-8f58a1667fc7.png)

Nie wiem... Uaktualnij? Może lepiej Uzupełnij? Proponuj? :) Ale czy w ogóle "opcje"?

**Comment by borysiasty** [comment]
Do 2.18 daję **Wczytaj opcje z warstwy**, ale nie mam przekonania, więc w Transifeksie (przyszły 3.0 na dzień pisania tego komentarza) zostaje po staremu.

**Comment by miszokienka** [comment]
**Wczytaj opcje z warstwy** wg mnie bardzo dobrze pasuje.

**Comment by borysiasty** [comment]
No to tak zmieniłem.
