### ISSUE TITLE
Core plugins

### ISSUE THREAD

**Issue by erpas** [Cracert/QGIS-trans-PL#3]
Nie mogę się doszukać jednoznacznego, istniejącego tłumaczenia 'core plugins'. W opisie menedżera wtyczek jest odniesienie do 'wtyczek dostarczanych z programem instalacyjnym', ale mam propozycję, aby nazywać je wtyczkami RDZENNYMI. Co Wy na to?

**Comment by Cracert** [comment]
Mnie 'rdzenny' kojarzy się raczej z ludnością niż z wtyczkami :) 

Ten termin jest bardzo rzadko używany i myślę że można go dać w długiej formie opisowej, pozostawiając krótki termin 'wtyczki' dla tych doinstalowywanych.
Ewentualnie nazwać je 'wtyczki wewnętrzne' albo 'wtyczki stałe', chociaż to też brzmi dziwnie.

**Comment by erpas** [comment]
a wtyczki domyślne?

**Comment by borysiasty** [comment]
Nie mam cienia pomysłu, jak je zgrabnie nazwać i stąd w odruchu rozpaczy wykombinowałem te _instalowane z programem_ czy jak tam było. Ale ani ten mój wynalazek, ani żadna z powyższych propozycji jakoś mi nie brzmi :(

**Comment by erpas** [comment]
Zostawiam tłumaczenie opisowe.
