### ISSUE TITLE
Poważne błędy w okienku Opcje -> Renderowanie -> Rastry

### ISSUE THREAD

**Issue by borysiasty** [Cracert/QGIS-trans-PL#30]
- [x] Dialog Options -> zakładka Rendering -> sekcja Rasters powinna być przetłumaczona na **Rastry**, a jest **Siatka**!

- [x] Nieco niżej są trzy listy rozwijalne "Bez rozciągania/Rozciągnij do MinMax/itp.", a pod nimi lista pozwalająca zdefiniować, co się kryje pod tym pojęciem _MinMax_ (z trzema opcjami do wyboru: min-max po obcięciu skrajnych wartości wedle skumulowanej liczby pikseli, pełne min-max albo średnia +- odchylenie). Tłumaczenie całego tego widgetu trzeba przepracować, bo teraz wychodzi _Ogranicz do (min/max): łącznej liczby pikseli_, co nie ma wiele wspólnego z faktycznym znaczeniem tego ustawienia! Ogólny sens powinien być mniej więcej taki: "Użyty powyżej zakres _MinMax_ oznacza: Minimum / maksimum (zakres danych źródłowych) po odrzuceniu skrajnych wartości wyznaczonych na podstawie skumulowanej liczby pikseli".

Czyli nie _Ogranicz do (min/max)_ tylko raczej _gdzie MinMax oznacza_ (im dłużej nad tym myślę, tym bardziej podoba mi się tu termin "gdzie"). Dodam, że w oryginale jest _Limits (minimum/maximum)_.

Trudniej będzie z tą pierwszą wybieralną wartością, która brzmi _łącznej liczby pikseli_ (ang. _Cumulative pixel count cut_). Skoro kolejna pozycja to po prostu _Minimum - maximum_, to może tutaj dać _Minimum - maximum z obcięciem skrajnych wartości_

W kolejnej linii definiujemy te skrajne wartości (2 - 98% skumulowanej liczby pikseli), więc może tutaj przenieść opis i wyjdzie _gdzie Skrajne Wartości wyznacza ...  - ... % skumulowanej liczby pikseli_
To ostatnie brzmi tak sobie, ale idea jest taka, żeby wytłumaczenie, o jakie skumulowanie chodzi przenieść z pola wyboru do tej linijki.

@Cracert, @alinager, @erpas, @milenanv, Marta - proszę o burzę mózgów

**Comment by borysiasty** [comment]
W 2.18 dałem roboczo tak (i to są moje wstępne propozycje do Transifeksa):

~~Ogranicz do (min/max)~~ -> **Gdzie zakres MinMax wyznacza** (ang. *Limits (minimum/maximum)*)
~~łącznej liczby pikseli~~ -> **histogram bez skrajnych wartości** (ang. *Cumulative pixel count cut*)
~~Łączna liczba pikseli~~ -> **Granice obcięcia histogramu** (ang. *Cumulative pixel count cut limits*)

Kto to tłumaczył? :)

**Comment by Cracert** [comment]
Na razie zmieniłem w Transie na wersje z Twojego ostatniego wpisu.
Zamykamy czy zostawiamy do dyskusji?

**Comment by borysiasty** [comment]
Jeśli to jest do przełknięcia, to zamknijmy, szkoda czasu. Dzięki!
