### ISSUE TITLE
Domyślny wybór w trybie graficznym ...

### ISSUE THREAD

**Issue by Cracert** [Cracert/QGIS-trans-PL#31]
jest przetłumaczony jako

_Zaznacz obiekty w obszarze lub wskazując_

Niby poprawnie, ale strasznie to długie!

**Comment by borysiasty** [comment]
Propozycja: **Zaznacz obiekty prostokątem lub kliknięciem** 

Chodzi o tooltip domyślnego narzędzia zaznaczania w *Pasku narzędzi atrybutów*

**Comment by Cracert** [comment]
Propozycja przyjęta i tekst zmieniony.
