### ISSUE TITLE
Processing: Convert format

### ISSUE THREAD

**Issue by borysiasty** [Cracert/QGIS-trans-PL#32]
Processing -> OGR [Konwersja] -> Convert format

*Converted* przetłumaczono na *Warstwa ze zmienionym typem geometrii*, tymczasem chodzi o konwersję formatu pliku, a nie typu geometrii. Może po prostu *Warstwa wyjściowa* ?

**Comment by Cracert** [comment]
Zmienione trzy wystąpienia na `Warstwa wyjściowa`
