### ISSUE TITLE
Przesunięcie krzywych

### ISSUE THREAD

**Issue by borysiasty** [Cracert/QGIS-trans-PL#33]
Ustawienia -> Opcje -> Digitalizacja 

*Curve offset tool* przetłumaczono na enigmatyczne *Przesunięcie krzywych*. Chodzi o ustawienia narzędzia z paska zaawansowanej edycji. Może już lepiej by było *Narzędzie przesuwania krzywych*?

**Comment by Cracert** [comment]
Zmienione
