### ISSUE TITLE
Domyślny tryb przyciągania

### ISSUE THREAD

**Issue by borysiasty** [Cracert/QGIS-trans-PL#34]
Ustawienia -> Opcje -> Digitalizacja

Jest:
Domyślny tryb przyciągania: wierzchołka | segmentu | ...

Propozycja:
**do** wierzchołka, **do** segmentu etc.

**Comment by Cracert** [comment]
Zmieniłem `do wierzchołka`, ale `segmentu` nie widzę.

**Comment by borysiasty** [comment]
Widocznie zmienił się źródłowy string. Teraz są trzy pozycje: ``Vertex`` | ``Vertex and segment`` | ``Segment``. Pierwszą właśnie poprawiłeś na "do wierzchołka", pozostałe są nieprzetłumaczone.

Analogiczne trzy pozycje są w *Pasku narzędzi przyciągania*. Jest tam też druga lista: ``All layers`` | ``Active layer`` | ``Advanced configuration``. W tych dwóch listach również poleciałbym z małej litery *do wierzchołka*, *do wszystkich warstw*. Miejsce jest. 

Tylko nie ryzykowałbym tej zmiany w Transifeksie, bo *Vertex* i *Segment* mogą być użyte jeszcze w milionie innych miejsc.

**Comment by Cracert** [comment]
Poprawione.

> Jest tam też druga lista: ``All layers`` | ``Active layer`` | ``Advanced configuration``. W tych dwóch listach również poleciałbym z małej litery *do wierzchołka*, *do wszystkich warstw*. Miejsce jest. 

W Transie nie ma żadnej z tych fraz:  ``All layers`` | ``Active layer``

**Comment by borysiasty** [comment]
Dzięki, po następnym updacie będą: https://github.com/qgis/QGIS/commit/053fec89a2f

**Comment by borysiasty** [comment]
Tu wszystko wydaje się już zrobione.
