### ISSUE TITLE
Wiele serwerów WMS zostało dodanych do listy serwerów - nieścisłość

### ISSUE THREAD

**Issue by borysiasty** [Cracert/QGIS-trans-PL#36]
Po wciśnięciu *Dodaj domyślne serwery* w oknie *Dodaj warstwy z serwera WM(T)S* pojawia się okienko o tytule *WMS proxy*, które głosi: *Wiele serwerów WMS zostało dodanych do listy serwerów*.

Tymczasem to *wiele* to... dwa serwery.

**Comment by Cracert** [comment]
Zmienione na

`Serwery WMS zostały dodane do listy.`
