### ISSUE TITLE
Styl QGIS grupy (niezrozumiałe)

### ISSUE THREAD

**Issue by borysiasty** [Cracert/QGIS-trans-PL#37]
Ustawienia -> Opcje -> Ogólne -> Program -> czekboks *Styl QGIS grupy*

Jest: *Styl QGIS grupy*
W oryginale: *QGIS-styled group boxes*
Propozycje: Hmmm.... Nie wiem...
 - Użyj stylu QGIS dla grup widżetów
 - Użyj stylu QGIS do grupowania widżetów
 - Grupuj w stylu QGIS ;)
 - QGIS-owe grupy widżetów

O co w ogóle chodzi: Przełącz tego czekboksa i po około sekundzie zobaczysz zmianę stylu ramek grup.

**Comment by Cracert** [comment]
Zmienione na `Użyj stylu QGIS dla grup widżetów`
