### ISSUE TITLE
Wtyczka Processing vs Geoprocesing (niespójność)

### ISSUE THREAD

**Issue by borysiasty** [Cracert/QGIS-trans-PL#38]
Nazwę wtyczki Processing przetłumaczyliśmy na Geoprocesing. Ponieważ jest to coraz ważniejsza część QGIS-a i niebawem zapewne przestanie być wtyczką, a większość wtyczek będzie jej podlegała, użytkownicy będą coraz częściej spotykać nieprzetłumaczone teksty zawierające nazwę Processing. Jest to też nazwa związanych z nią katalogów itp.

W związku z tym od QGIS-a 3.0 **proponuję wrócić do oryginalnej nazwy Processing**.

**Comment by Cracert** [comment]
Zmienione w wielu miejscach na `processing`.
