### ISSUE TITLE
Działanie kółka na myszce (drobiazg)

### ISSUE THREAD

**Issue by borysiasty** [Cracert/QGIS-trans-PL#39]
**gdzie**: Ustawienia -> Opcje -> Narzędzia mapy -> Przesuwanie i powiększanie
**jest**: Działanie kółka na myszce
**powinno być**: Działanie rolki myszy, ew. Działanie kółka myszy, ew. Działanie kółka myszki
**dlaczego**: Kółko nie jest na myszce. W znacznej większości swojej objętości jest wewnątrz myszki.

**Comment by Cracert** [comment]
W Transifexie znalazłem tylko `Używanie kółka myszki`.

**Comment by borysiasty** [comment]
Racja, tiket nieaktualny.
