### ISSUE TITLE
Map canvas

### ISSUE THREAD

**Issue by erpas** [Cracert/QGIS-trans-PL#4]
Próbuję jakoś opisowo tłumaczyć 'map canvas', ale mam coraz większą ochotę na użycie wyrażenia 'kanwa mapy'. Dajcie proszę znać, co myślicie. Rozważam też 'obszar mapy' lub 'podstawa mapy'.

**Comment by Cracert** [comment]
Rozważaliśmy jakiś czas termu różne wersje, ale przyjęliśmy 'obszar mapy' jako najbardziej zrozumiały termin.

**Comment by borysiasty** [comment]
Z wyżej wymienionych pasuje mi jedynie _obszar mapy_, choć i on nie jest idealny, bo może się kojarzyć z zasięgiem. Poza tym teoretycznie _map canvasów_ może być kilka. Teraz jest jeden główny + jeden podgląd zasięgu, kiedyś zapewne pojawi się możliwość otwierania wielu głównych map. No właśnie, ja na niego mówię czasem po prostu _mapa_. 

Problem w tym, że termin _map_ jest już używany w kompozycjach wydruku, gdzie każdy _map_ jest obrazem głównego _map canvasu_ z indywidualnie ustawionymi parametrami: skala, zasięg, widoczność warstw, filtr obiektów, styl itp (dwóch ostatnich chyba nie ma jak ustawić w Desktopie, ale są dostępne w Serverze przy żądaniu GetPrint).

**Comment by erpas** [comment]
Ok, zostaje _obszar mapy_.
