### ISSUE TITLE
Grafika zamiast Wykresy

### ISSUE THREAD

**Issue by borysiasty** [Cracert/QGIS-trans-PL#40]
Gdzie: Drzewo algorytmów Processing -> Geoalgorytmy QGIS -> nazwa gałęzi
Jest: **Grafika**
Powinno być: **Wykresy** 
Oryg. ang.: **Graphics**

**Comment by Cracert** [comment]
Zmieniłem w kilku miejscach (8 szt.) na liczbę pojedynczą `Wykres`.
