### ISSUE TITLE
QGIS 2.14 Processing: Połącz warstwy wektorowe

### ISSUE THREAD

**Issue by alinager** [Cracert/QGIS-trans-PL#41]
Processing -> Geoalgorytmy QGIS [Ogólne narzędzia wektorowe] -> Połącz warstwy wektorowe

W QGIS 2.14 'Merged' przetłumaczono na 'Raster złączony', tymczasem łączymy wektory. W QGIS 2.18 jest już prawidłowo 'Złączony'.

**Comment by borysiasty** [comment]
Czy w ogóle wspieramy jeszcze tłumaczenia 2.14? Jeśli nikt nie ma na to ochoty, to proponuję zamknąć.
@Cracert @alinager @milenanv

**Comment by Cracert** [comment]
Ja nie ruszam już 2.14, tylko koncentruję się na Transifexie, choć nadal nie mam jasności, gdzie i kiedy te tłumaczenia lądują.
Z tego co przeglądałem w repo githuba, pliki tłumaczeń są synchronizowane w ostatniej chwili przed wydaniem wersji. Czyli w conocnych kompilacjach nie powinno być aktualnych zmian, co jest fatalnym rozwiązaniem. Chyba, ze coś przeoczyłem.

**Comment by milenanv** [comment]
Ja jeśli tłumaczę, to już tylko na Transifexie. Nie wiem jak są synchronizowane pliki i zgadzam się, że Transifex to krok wstecz i spadek jakości.
2.14 ciągle służy nam do szkoleń, może powinniśmy trochę go poprawić, przynajmniej w oczywistych podstawowych miejscach... a to się da chyba tylko ze źródeł.

**Comment by Cracert** [comment]
Nie ma już tego w Transifexie. Zamykamy.
