### ISSUE TITLE
Właściwości projektu -> Warstwy -> Przeszukiwana

### ISSUE THREAD

**Issue by borysiasty** [Cracert/QGIS-trans-PL#43]
Wydaje misię, że to *przeszukiwana* jest mało zrozumiałe. W oryginale jest *identifiable*.

**Comment by erpas** [comment]
Skoro mamy ją później w doku _Wynik identyfikacji_, to może _identyfikowana_?

**Comment by borysiasty** [comment]
Ale _identyfikowane_ to są obiekty na niej... Póki co, nie wpadłem na żaden sensowny pomysł, więc chyba niech zostanie _przeszukiwana_...
