### ISSUE TITLE
Processing -> Opcje -> Źródła danych

### ISSUE THREAD

**Issue by borysiasty** [Cracert/QGIS-trans-PL#44]
Gdzie: Gałąź ustawień Processingu 
Tekst angielski: *Providers*
Znaczenie: *Dostawcy algorytmów*
Aktualne tumaczenie: *Źródła danych*
Powinno być: Proponuję po prostu *Algorytmy*

**Comment by Cracert** [comment]
Zmienione.

**Comment by borysiasty** [comment]
Jak zobaczyłem na żywo, to jednak mi się nie podoba. Myślałem o **Źródłach algorytmów**, ale po namyśle proponuję zdecydowanie **Dostawcy algorytmów**. 

Może trochę pachnie nowomową z własnościowych programów, ale jest jednoznaczne i w kilku miejscach już użyte. Prędzej czy później i tak trzeba będzie się zmierzyć z terminem *provider*, bo jest w QGIS-ie często używany i tłumaczenie go jako *źródło* prowadzi prosto w pokrzywy (np. *layer provider* i *layer source* to dwie zupełnie inne rzeczy).

**Comment by Cracert** [comment]
OK.

Zmieniam w takim razie we wszystkich 66 frazach *provider* na **dostawca**.
