### ISSUE TITLE
Błędy w oknie wyboru bazy danych do zapisu domyślnego stylu warstwy Postgis / SpatiaLite

### ISSUE THREAD

**Issue by borysiasty** [Cracert/QGIS-trans-PL#46]
Gdzie: *Layer Styling* (panel stylowania na żywo) -> *Save as default* -> okienko *Zapisz domyślny styl jako:* (pokazuje się chyba tylko dla warstw bazodanowych, w każdym razie postgisowych i spatialitowych)

Jest: **Zapisz domyślny styl jako:**
Powinno być: **Zapisz domyślny styl w:**

Jest: **Źródło bazy danych** 
Powinno być: **Żródłowa baza danych** (bo to alternatywa dla: *Lokalna baza danych*)

**Comment by borysiasty** [comment]
![blad_tlum](https://user-images.githubusercontent.com/1000043/31292614-7500fb94-aad4-11e7-86ba-2f9531640b98.png)

**Comment by Cracert** [comment]
Poprawione po dwa wystąpienia każdego.
