### ISSUE TITLE
Informuj o konieczności zapisu, gdy projekt i źródło ulegną zmianie [niejasne]

### ISSUE THREAD

**Issue by borysiasty** [Cracert/QGIS-trans-PL#47]
**Gdzie**: Główne okno Opcji -> Ogólne -> Pliki Projektu -> Czekboks
**Jest**: Informuj o konieczności zapisu, gdy projekt i źródło ulegną zmianie
**Ang**: Prompt to save project and data source changes when required
**Propozycja**:  Ostrzegaj o niezapisanych zmianach w projekcie i na warstwach.

Niby można się domyślić, o co chodzi, ale do ideału klarowności trochę brakuje. Nie źródło, tylko dane. On nie informuje, tylko pyta. I bynajmniej nie w momencie, gdy ulegną zmianie.

**Comment by Cracert** [comment]
Zmienione.
