### ISSUE TITLE
Dodaj jako Ulubione -> Dodaj do Ulubionych

### ISSUE THREAD

**Issue by borysiasty** [Cracert/QGIS-trans-PL#48]
**Gdzie**: Menu kontekstowe Panelu Przeglądarki, może gdzie indziej też.
**Jest**: Dodaj jako Ulubione
**Powinno być**: znacznie bardziej przyjęło się *Dodaj do Ulubionych* (w Googlach ponad 10 tys razy więcej trafień).

**Comment by Cracert** [comment]
To już było zmienione.
