### ISSUE TITLE
Select and deselect

### ISSUE THREAD

**Issue by erpas** [Cracert/QGIS-trans-PL#5]
Teraz 'select' tłumaczone jest jako 'wybierz'. Ale 'deselect' to 'zlikwiduj zaznaczenie' (na pasku Atrybuty) i 'odznacz' (w tabeli atrybutów).
Co Wy na to, aby ujednolicić tłumaczenie i używać 'zaznacz' i 'odznacz'?

'Selected features' byłyby wówczas konsekwentnie 'obiektami zaznaczonymi' a nie 'wybranymi'.
Z kolei narzędzia wyboru musiałyby zostać przemianowane na narzędzia zaznaczania.
Hmm.. dość poważna zmiana, ale wtedy unikamy nieporozumień, czy 'wybrany' oznacza to samo, co 'zaznaczony' i mamy uproszczenie 'likwidacji zaznaczenia'.

**Comment by erpas** [comment]
'Clear highlights', 'Highlight all' z menu kontekstowego okna wyników identyfikacji też byłoby do zmiany na 'Wyczyść zaznaczenie', 'Zaznacz wszystkie'
Na pasku narzędziowym, polecenie 'Select by Freehand' obecnie tłumaczone jest jako 'wybierz zaznaczeniem' - proponuję 'Zaznacz obiekty obrysem'.

**Comment by borysiasty** [comment]
Ujednolicenie jest konieczne, ale nie potrafię się zdecydować, w którą stronę. Może _zaznaczenie_ brzmi mi odrobinkę jaśniej, niż _wybór_, ale wstrzymuję się od głosu.

**Comment by erpas** [comment]
Proponuję powrócić do ujednolicenia tłumczenia 'selected' na zaznaczone. Jeżeli nie będzie głosów sprzeciwu, to postaram się zdążyć z tym do wydania 2.10.

**Comment by Cracert** [comment]
Zmiana w którąkolwiek stronę będzie lepsza niż dwa różne tłumaczenia. **Zaznaczone** brzmi dobrze. 

**Odznacz** czy **zlikwiduj zaznaczenie**?

Musimy tylko gdzieś wyraźnie (sobie) zaznaczyć, żeby nie powrócić w przyszłości przy nowych tłumaczeniach do 'wybranych'.

**Comment by erpas** [comment]
Odznacz.

W dniu 22 czerwca 2015 22:56 użytkownik Robert Szczepanek <
notifications@github.com> napisał:

> Zmiana w którąkolwiek stronę będzie lepsza niż dwa różne tłumaczenia.
> _Zaznaczone_ brzmi dobrze.
> 
> _Odznacz_ czy _zlikwiduj zaznaczenie_?
> 
> Musimy tylko gdzieś wyraźnie (sobie) zaznaczyć, żeby nie powrócić w
> przyszłości przy nowych tłumaczeniach do 'wybranych'.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Cracert/QGIS-trans-PL/issues/5#issuecomment-114260100
> .

## 

Używam wolnego oprogramowania:
https://www.gnu.org/philosophy/philosophy.pl.html

**Comment by erpas** [comment]
Trochę zaspałem przed wydaniem... i nie dałem znać, ale zmieniłem wszystko, co widziałem i wydaje się, że można sprawe zamknąć.

**Comment by Cracert** [comment]
Dzięki za zmiany.
W takim razie zamykamy temat.
