### ISSUE TITLE
Crash dumped -> Awaria przy zrzucie

### ISSUE THREAD

**Issue by borysiasty** [Cracert/QGIS-trans-PL#50]
Gdzie: **Tytuł okna z informacją o awarii i położeniu zrzutu jądra**
Oryg.: **Crash dumped**
Jest: **Awaria przy zrzucie**
Problem: **Brak sensu, demonstracja braku pojęcia o komputerach**
Propozycja: **Awaria** (samo)

**Comment by Cracert** [comment]
Nigdzie tego nie widzę. Są za to inne kwiatki ze słowem `crash`. 

Zmieniłem:
* **Moduł zawiesił się lub został ubity** -> **Moduł uległ awarii lub został wyłączony**
* *:( QGIS Crashed* -> **Awaria :(**
* i kilka innych przy okazji

**Comment by borysiasty** [comment]
Racja, w 3.0 nie ma już tego okna.

@Cracert: No nie, **wyłączony** to raczej *disabled*, a na pewno nie *killed*. Ja bym dał jedno z poniższych (w kolejności od najbardziej do najmniej fachowego określenia):
 
1. zabity (przyznam, że dla początkujących userów może brzmieć lekko żargonowo)
2. unicestwiony
3. przerwany
4. eeewentualnie zatrzymany, ale tu już wkraczamy w strefę dezinformacji ;)
 
Natomiast faktycznie tamtego okna z 2.18 nie ma już w masterze.

**Comment by Cracert** [comment]
`Module crashed or killed`dla zwykłego użytkownika oznacza, że moduł przestał działać. A to czy sam się wykrzaczył, czy ktoś/coś go ubiło, nie ma żadnego znaczenia. 

Zostawmy może samo **Moduł uległ awarii**.

**Comment by borysiasty** [comment]
Po pierwsze, QGIS ma **niezwykłych** użytkowników, którzy zasługują na najlepsze możliwe tłumaczenie ;-) (Panie Google, proszę zaprotokołować, że tak napisałem).

A po drugie - tutaj nie będę darł szat, ale generalnie jestem przeciwny zubażaniu treści tylko dlatego, że *zwykli użytkownicy nie zrozumio*. W takim wypadku należałoby sugerować power userom (do których taki zwykły użytkownik może się zwrócić, natrafiwszy na przedmiotowy błąd), żeby używali QGIS-a w oryginale... 

Nie mówiąc już o tym, że początkujący użytkownik pewnie nie używa GRASS-a, a ten komunikat, jeśli się nie mylę, dotyczy tylko jego modułów.

**Comment by Cracert** [comment]
Zaawansowani użytkownicy i tak pewnie używają wersji angielskich. A pozostałym wolałbym przekazywać komunikaty w możliwie łagodnej i zrozumi(a)łej formie. 

**Moduł został ubity**. Czyli kto go ubił? Gajowy Marucha?

**Comment by borysiasty** [comment]
Nigdzie nie broniłem formy *ubity*, tylko *zabity* ;p 

Ja tam nie jestem zaawansowanym użytkownikiem, ale na angielski przełączam się dopiero, jak nie mogę rozszyfrować tekstu przetłumaczonego ;)
