### ISSUE TITLE
Zarządzaj vs Zarządzanie wtyczkami, bazami 

### ISSUE THREAD

**Issue by borysiasty** [Cracert/QGIS-trans-PL#51]
Mamy takie dwie pozycje w menu:
Wtyczki -> Zarządza**j** wtyczkami
Bazy danych -> Zarządza**nie** bazami

Proponuję ujednolicić bezosobowo do **Zarządzanie** wtyczkami.

**Comment by Cracert** [comment]
Zmieniłem jeszcze zarządzanie **połączeniami, certyfikatami, obiektami, kolorami, wartościami komórek rastra, danymi treningowymi**.

**Comment by borysiasty** [comment]
@Cracert, i to trafi do 3.0, prawda?

**Comment by Cracert** [comment]
Z ostatnich wyjaśnień Warnera tak wynika, że z Transifexa zasysają przed samym budowaniem paczek.
