### ISSUE TITLE
Okno Opcji -> Ogólne

### ISSUE THREAD

**Issue by borysiasty** [Cracert/QGIS-trans-PL#52]
Mamy w tym oknie kilka niezrozumiałych bądź groteskowych tłumaczeń:

- [x] **Motyw (wymaga ponownego uruchomienia QGIS)** *(Style (QGIS restart required))*, a zaraz pod nim **Motyw interfejsu** *(UI Theme)*. Pierwsze to styl widżetów, drugie to schemat kolorystyczny, ale z tłumaczenia nie wynika żadna różnica. Może pierwsze zmienić na **Motyw interfejsu** a drugie na **Motyw kolorystyczny interfejsu**? Brzmi brzydko, ale jest jasne. Druga propozycja: **Motyw interfejsu (wymaga ponownego uruchomienia QGIS)** oraz **Motyw interfejsu (kolory)**

- [x] Czcionka: **domyślny Qt** *(Qt default)* - powinno być co najmniej **domyślna Qt** (albo jeszcze ładniej)

- [x] **Limit czasu dla komunikatów** *(Timeout for timed messages or dialogs)* - proponuję **Czas wyświetlania komunikatów** (limit czasu jest w tym kontekście mało zrozumiały)

- [x] **Styl QGIS grupy** - patrz #37

- [x] **Informuj o konieczności zapisu, gdy projekt i źródło ulegną zmianie** - patrz #47

**Comment by Cracert** [comment]
Przy pierwszym punkcie wybrałęm drugą opcję:
* Motyw interfejsu (wymaga ponownego uruchomienia QGIS) 
* Motyw interfejsu (kolory)

Nie zamykam, bo tam jest jeszcze sporo rzeczy.

**Comment by miszokienka** [comment]
A ja bym przy pierwszym dał po prostu **Styl (wymaga ponownego uruchomienia QGIS)** i **Motyw interfejsu**
Reszta jak dla mnie ok.

**Comment by borysiasty** [comment]
To dałem **Styl interfejsu (wymaga...**
