### ISSUE TITLE
Okno Opcji -> Źródła danych

### ISSUE THREAD

**Issue by borysiasty** [Cracert/QGIS-trans-PL#53]
- [x] **Atrybuty obiektów i tabele** *(Feature attributes and table)* - moja propozycja: samo **Tabela atrybutów** najlepiej pasuje do zawartości tej sekcji. Ewentualnie **Tabela i formularz atrybutów**.

- [x] **Właściwości tabeli atrybutów** *(Attribute table behaviour)* - np. *Pokaż wszystkie obiekty*, *Pokaż zaznaczone obiekty* itp. To nie są do końca właściwości, ale dosłowne *Zachowanie* też nie będzie najlepsze. Może **Zawartość tabeli atrybutów**.

- [x] **Szukaj poprawnych obiektów w oknie przeglądarki** *(Scan for valid items in the browser dock)*. Po pierwsze nie ma już okna, po drugie jakie obiekty, po trzecie jakie poprawne. Szybka propozycja: **Skanując dysk w panelu przeglądarki...** albo coś takiego.

- [x] **Szukaj w plikach skompresowanych (.zip) w oknie przeglądarki** -> okno do zmiany na **panel**.

- [x] **Jeśli można, wykonaj zapytania po stronie serwera** -> zmieniłbym na **wykonuj**

**Comment by Cracert** [comment]
**Właściwości tabeli atrybutów** *(Attribute table behaviour)* nie widzę w Transifexie.

**Comment by borysiasty** [comment]
@Cracert pisze: 
> Właściwości tabeli atrybutów (Attribute table behaviour) nie widzę w Transifexie.

Gdyż zmieniono oryginalny tekst na amerykański: **Attribute table behavior**.

**Comment by Cracert** [comment]
OK. Zmienione na **Zawartość tabeli atrybutów**.
