### ISSUE TITLE
Tooltipy narzędzi z paska etykietowania

### ISSUE THREAD

**Issue by borysiasty** [Cracert/QGIS-trans-PL#55]
- [x] Tooltip klawisza włączającego okno opcji kartodiagramów

**Opcje warstwy wykresu** (*Layer Diagram Options*) -> propozycja: **Opcje wykresów** (przez analogię do sąsiedniego *Opcje etykietowania*) albo **Opcje kartodiagramu** (patrz #56)

-------

- [x] Tooltip narzędzia ukrywania etykiety/diagramu
Tłumaczenie jest nieco niespójne, poza tym przynajmniej u mnie zlewają się wiersze i wychodzi tak:

**Wyświetl/ukryj etykiety i wykresy Kliknij na znaczniku aby wyświetlić Shift+kliknięcie lub znacznik etykiety lub wykresu, aby ukryć Działa na aktualnie edytowanej warstwie**

Oryginał (z zachowaniem końców wierszy):

*Show/Hide Labels And Diagrams
Click or marquee on feature to show label and diagram
Shift+click or marquee on label or diagram to hide it
Acts on currently active editable layer*

Propozycja (kropki trochę uratują brak łamania):

**Wyświetl/ukryj etykiety i wykresy. Kliknięcie na znaczniku wyświetla, shift+kliknięcie ukrywa (uwaga, działa na aktualnie edytowanej warstwie).**

**Comment by Cracert** [comment]
Zmienione na **Opcje kartodiagramu**.
