### ISSUE TITLE
Wykresy czy Kartodiagram?

### ISSUE THREAD

**Issue by borysiasty** [Cracert/QGIS-trans-PL#56]
Wszędzie, gdzie jest  mowa o kartodiagramach, widzę określenie **wykresy**. W oryginale jest *diagram*. Osobiście wolałbym określenia **wykres** używać tam, gdzie mowa o konkretnych elementach kartodiagramu oraz o różnych "niemapowych" wykresach z części analitycznej (które prędzej czy później na pewno zawitają np. w layoucie wydruku), natomiast dla całej warstwy używać formy **kartodiagram**. Czyli: 
 - **Wykres** (zakładka w oknie opcji warstwt wektorowej) -> **Kartodiagram**
 - **Opcje warstwy wykresu** (tooltip klawisza w Pasku Etykietowania) -> **Opcje kartodiagramu** (przez analogię do sąsiadujących *Opcji etykietowania*) 
 - **Właściwości warstwy wykresu** (tytuł okna) -> **Właściwości kartodiagramu**
 - **Wykres tekstowy** (pozycja na liście wyboru typu wykresu) -> po prostu **Tekst**
 - **Bez wykresu**, **Wykres kołowy** (tamże) -> zostawić jak jest

**Comment by Cracert** [comment]
Też o tym już od dawna myślałem. Jestem na TAK.

**Comment by Cracert** [comment]
Poprawione, ale jeszcze do przeglądnięcia, bo nie mam pewności.

**Comment by borysiasty** [comment]
@Cracert: Zakładkę we właściwościach warstwy wektorowej nazwałeś **Kartodiagramy**. Proponuję w liczbie pojedynczej.

**Comment by Cracert** [comment]
Zmienione.
