### ISSUE TITLE
Podpowiedź w konsoli Pythona

### ISSUE THREAD

**Issue by borysiasty** [Cracert/QGIS-trans-PL#57]
**jest:** Dostęp do interfejsu QGIS API uzyskać można za pomocą wyrażenia iface. Więcej informacji otrzymasz wpisując help(iface)

**czyli:** Za długo (zabiera dwie linijki), zawiera pleonazm, błąd rzeczowy i interpunkcyjny.

**oryg:** Use iface to access QGIS API interface or Type help(iface) for more info

**propozycje:** 
    - Dostęp do API uzyskasz poprzez obiekt iface. Więcej informacji udzieli help(iface). 
    - Obiekt iface zapewnia dostęp do API. Więcej informacji udzieli help(iface).

**Comment by Cracert** [comment]
Zmieniłem na **Dostęp do API uzyskasz poprzez obiekt iface. Więcej informacji w help(iface).**

**Comment by borysiasty** [comment]
@Cracert: wiem, że to niuans i nikt tam nie zagląda, ale ja akurat codziennie ;D więc tylko krótkie pytanie: Nie upieram się, ale co myślisz o: Więcej informacji **pod** help(iface)? Bo to **w** sugeruje, że informacje są wewnątrz funkcji, a nie jej wynikiem ;)
