### ISSUE TITLE
Panel skalowania kafli

### ISSUE THREAD

**Issue by borysiasty** [Cracert/QGIS-trans-PL#59]
**gdzie:** nazwa panelu
**jest:** Panel skalowania kafli
**oryg:** Tile Scale Panel
**problem:** brak sensu w tłumaczeniu ;)
**znaczenie**: Panel z suwakiem skali, ograniczonym do szeregu skalowego warstwy kaflowej obecnej w projekcie.
**propozycja:** Sensownej brak. Panel skalowania kaflowego? :) Mogłoby być: Panel skalowania dyskretnego, Panel szeregu skalowego, ale combobox skali ma już dyskretny szereg.

**Comment by Cracert** [comment]
Zmieniłem na **Panel szeregu skalowego**. W razie czego wrócimy do tematu.

**Comment by borysiasty** [comment]
Wolałbym tego jeszcze nie zamykać, bo samo "szereg skalowy" znacznie bardziej kojarzy mi się ze zwykłym szeregiem skalowym, który ustawiasz we właściwościach projektu i widzisz jako rozwijalną listę w comboboksie "Skala". A to jest zupełnie alternatywny szereg, brany z warstwy TMS albo WMS-T.

**Comment by borysiasty** [comment]
Więc o ile stara wersja była enigmatyczna, to nowa jest wprost myląca...

**Comment by borysiasty** [comment]
To zrobiłem jeszcze inaczej. Paskudnie brzydko, ale niemyląco:
**Zoom warstwy kafli**

Tadaaam, teraz zabijajcie.
