### ISSUE TITLE
Placement

### ISSUE THREAD

**Issue by erpas** [Cracert/QGIS-trans-PL#6]
Na ogół 'placement' tłumaczone jest jako 'położenie'. W dialogu praw autorskich jest 'umiejscowienie'.

**Comment by Cracert** [comment]
Chyba faktycznie lepiej byłoby dać tam 'położenie'.

**Comment by borysiasty** [comment]
+1 za _położeniem_, gdziekolwiek jest to jednoznaczne. Krócej, jaśniej i zgrabniej.

**Comment by Cracert** [comment]
Poprawione we wszystkich wystąpieniach.
