### ISSUE TITLE
Wyświetl informację o rastrze -> Informacje

### ISSUE THREAD

**Issue by borysiasty** [Cracert/QGIS-trans-PL#60]
Wszystkie wystąpienia ``^Information$`` są tłumaczone na  **Wyświetl informację o rastrze**.
Wyjątkowo to nie wina Transifeksa, tylko tak zostało przetłumaczone pierwsze wystąpienie i potem się powielało. Trzeba je wszystkie przejrzeć, bo prawdopodobnie jedno powinno zostać z rastrem.

**Comment by borysiasty** [comment]
Uwaga, dwa z nich to prawdopodobnie nazwy geoalgorytmów gdalinfo i ogrinfo. Czyli będzie **Wyświetl informację o rastrze** i **Wyświetl informację o wektorze**, tylko trzeba trafić, zapewne metodą prób i błędów z powodu braku informacji o lokalizacji stringów z Processingu.

**Comment by Cracert** [comment]
Przy wektorze i rastrze dałem tak jak napisałeś. W pozostałych miejscach wpisałem po prostu **Informacje**.

**Comment by borysiasty** [comment]
Nadal pierwsza zakładka w oknie właściwości warstwy rastrowej ma tę długą nazwę. Jutro to poprawię.

**Comment by borysiasty** [comment]
Gotowe
