### ISSUE TITLE
Akcje na tabelach i widokach PostGIS w Przeglądarce

### ISSUE THREAD

**Issue by borysiasty** [Cracert/QGIS-trans-PL#61]
**Gdzie:** ../src/providers/postgres/qgspostgresdataitems.cpp 310-353
**Jest:** ``Zmień nazwę %1 | Usuń %1 | Truncate %1`` podstawiane przez ``Widok | Tabela``
**Wychodzi tak**:

![truncate](https://user-images.githubusercontent.com/1000043/33420094-9825676e-d5ad-11e7-9c71-37c02965efc8.png)

**Propozycje** (tak zrobiłem w 2.18):
 - Zmień nazwę %1 -> **Przemianuj %1**
 -  Truncate %1 -> **Wyczyść %1**
 -  Widok -> **widok**
 -  Tabela -> **tabelę**

**Comment by Cracert** [comment]
Gotowe, ale sprawdź to proszę, bo robiłem tłumaczenie w ciemno, patrząc tylko na kod C++, nie skompilowane GUI.

**Comment by borysiasty** [comment]
Działa, dzięki!
