### ISSUE TITLE
Nazwy paneli

### ISSUE THREAD

**Issue by borysiasty** [Cracert/QGIS-trans-PL#64]
_**Panel** Warstw, **Panel** Zakładek przestrzennych, **Panel** dziennika komunikatów_...

Nazwy paneli widać w ich nagłówkach, w menu (prawomlaszcznym i zwykłym) oraz w oknie personalizacji. Jakiś czas temu do wszystkich nazw zostało dopisane słowo **Panel**, wyjątkiem jest _Processing Toolbox/Narzędzia processingu_, a także - chyba przez przeoczenie - _Layer Styling/Stylizacja warstw_ i _Results Viewer_. Powód dopisania był taki, że niektórzy użytkownicy podobno gubili się, widząc listę zatytułowaną **Panele**, a na niej pozycje: **Warstwy**, **Przeglądarka**, **Statystyki**, **Zaawansowana digitalizacja**.

Wydaje mi się, że nie dotyczy to naszych ponadprzeciętnie inteligentnych Rodaków. Może by tak wywalić słowo Panel? Co Wy na to?

**Comment by Cracert** [comment]
Jestem zdecydowanie **za** i od razy to zmieniam.

**Comment by Cracert** [comment]
Gotowe.

Czy to samo robimy z paskami narzędzi?

**Comment by borysiasty** [comment]
@Cracert Paski narzędzi dla spójności też bym zmienił.
