### ISSUE TITLE
Kategorie i nazwy algorytmów w Processingu

### ISSUE THREAD

**Issue by borysiasty** [Cracert/QGIS-trans-PL#65]
To jest najbardziej zaniedbany, a bardzo ważny zakątek interfejsu. 

1. Nazwy kategorii powodują tylko mętlik i wymagają solidnego przepracowania -> potrzebny chyba cały dzień na burzę mózgów.

2. I tak podstawą odnalezienia pożądanego algorytmu jest pasek filtra -> ważne jest przetłumaczenie (prawie) wszystkich nazw algorytmów.

**Comment by Cracert** [comment]
Jeśli dobrze widzę, to nazwy głównych kategorii są sortowane alfabetycznie. Jeśli tak, proponuję zamienić nazwy tak, żeby tworzyły logiczne grupy. Czyli: 

* `Analiza rastrowa`-> `Raster - analiza`
* `Narzędzia obróbki rastra` -> `Raster - obróbka`
* itd.

Mam jeszcze propozycję, żeby zmienić to nieszczęsne `Processing` na `Algorytmy`. Jest tak wpisane w opcjach (Dostawcy algorytmów) i brzmi nieźle. Tak samo nazywa się zresztą processing w oknie historii - `Algorithm`.

* `Processing` -> `Algorytmy`
* `Narzędzia processingu` -> `Algorytmy`

**Comment by borysiasty** [comment]
> Jeśli dobrze widzę, to nazwy głównych kategorii są sortowane alfabetycznie.

Dokładnie, nazwy algów także.

> Jeśli tak, proponuję zamienić nazwy tak, żeby tworzyły logiczne grupy.

+1

> Mam jeszcze propozycję, żeby zmienić to nieszczęsne Processing na Algorytmy

Hmm to duża zmiana, ale chyba fajna. W sumie bardziej pasuje mi takie tłumaczenie (i uznanie "Algorytmów" za taki trochę znak towarowy) niż dawne geoprocesing. Zastanawiam się nawet, czy nie przetłumaczyć nazwy wtyczki (to się robi na poziomie jej metadanych: name[pl]=Algorytmy), ale może to by była zbytnia ingerencja. Nazwy katalogów zostaną oczywiście oryginalne.

No i bardzo pasuje mi pozbycie się słowa "narzędzia", bo dla mnie narzędzia to Odpytaj, Zaznacz, Rysuj i cała ta grupa wzajemnie się wykluczających klawiszy w paskach narzędzi.

**Comment by borysiasty** [comment]
Po nocy: `Algorytmy` nadal misie lubią, ale trzeba pamiętać, że katalogi (np. na skrypty czy modele) nazywają się Processing, w zagranicznych materiałach i helpach jest Processing, nazwę wtyczki też bym zostawił w oryginale (czyli: *jeśli nie widzisz menu Algorytmy, włącz wtyczkę Processing*). W efekcie nie mam nic na przeciwko, o ile dopilnujemy, żeby **do każdego usera od średniozaawansowanego wzwyż dotarła wiadomość, że Algorytmy = Processing**. Obwieszczenie na Fejsie, Forum i Blogu powinno wystarczyć, tylko pytanie, czy wtedy tłumaczenie nie traci sensu :)

Widzę natomiast wariant pośredni: Zostawić `Processing` jako nazwę całego modułu/frameworku, ale `algorytmami` nazwać processingowy `toolbox` (dotychczasowe `narzędzia processingu`). W szczególności:
Tytuł panelu: `Narzędzia processingu` -> `Algorytmy`
Włącznik w menu: `Narzędzia processingu` -> `Panel algorytmów`

W ten sposób `Algorytmy` można uznać za domniemaną i skróconą formę `Algorytmów Processingu` (ale też nie blokują drogi do przemianowania całego Processingu). To jest chyba nieinwazyjne i niekontrowersyjne, więc proponuję zacząć od tego i wtedy podumać, czy brniemy dalej.

**Comment by borysiasty** [comment]
Zmienione.

Tytuł panelu: Narzędzia processingu -> **Algorytmy processingu**
Włącznik w menu: Narzędzia -> **Panel algorytmów**
