### ISSUE TITLE
 Toggle full screen mode - niewidoczne

### ISSUE THREAD

**Issue by Cracert** [Cracert/QGIS-trans-PL#66]
W menu `Widok`.

Jest przetłumaczone od miesięcy, ale w GUI jest wersja angielska. Jeśli to potwierdzisz @borysiasty , trzeba to zgłosić/poprawić w kodzie.

**Comment by borysiasty** [comment]
Ha, tego jednego wystąpienia nie znalazłeś (``Toggle Full Scr&een Mode``). Przetłumaczyłem.

**Comment by Cracert** [comment]
Na **&** w środku nie wpadłem :( ...

Dzięki!

**Comment by borysiasty** [comment]
W menu wszędzie są. Właśnie my je chyba wszędzie wycinamy, zamiast tłumaczyć, ale nie znam nikogo, kto by z nich korzystał :)
