### ISSUE TITLE
Jeszcze o dostawcach

### ISSUE THREAD

**Issue by borysiasty** [Cracert/QGIS-trans-PL#67]
Dziwnie to wygląda, nie?

![zrzut_20171220_085726](https://user-images.githubusercontent.com/1000043/34197444-d2a6e034-e566-11e7-8b6d-77c5565855d9.png)

Jakby chodziło o podmiot, który dostarczył te dane. Co o tym myślisz @Cracert? Można albo zignorować i zamknąć, albo przemyśleć wszystkie wystąpienia, żeby tu i ówdzie przetłumaczyć mniej dosłownie.

**Comment by Cracert** [comment]
Mamy tylko dwa wystąpienia tej frazy: dla wektora i rastra.   
Zmieńmy to może na proste **Informacje**, OK?

**Comment by borysiasty** [comment]
Oj nie, to jest tylko pierwsza sekcja Informacji, a tuż po lewej masz taką samą nazwę całej zakładki.
Jeśli już, to jakieś *Ogólne*, ale to nie oddaje treści. Kolejne sekcje zawierają głównie metadane, więc, najkrócej mówiąc, ta zawiera **nie-metadane**. W przypadku warstw gdalowych jest to +- wyjście gdalinfo / ogrinfo.

**Comment by Cracert** [comment]
Zmieniłem na 
* Informacje OGRinfo
* Informacje GDALinfo

**Comment by borysiasty** [comment]
No ale przecież poza GDAL-em jest jeszcze szesnastu innych dostawców: Spatialite, CSV, GPX, Postgis, WMS, WFS, ArcGIS itp. To wprowadza w błąd, że łączymy się ze wszystkim przez GDAL-a. Szczególnie, że podstawowy format wektorowy QGIS-a 3, czyli GeoPackage jest obsługiwany zarówno przez natywnego dostawcę, jak i przez GDAL-a i przy wszystkich kłopotach trzeba wiedzieć, jak się użytkownik podłączył. Ja już bym dał te **Ogólne**, tzn nic lepszego nie przychodzi mi do głowy.

**Comment by borysiasty** [comment]
*Informacja o warstwie*? Też niedobrze. *Format danych*? Ale jest tam zasięg i feature count. Chyba najlepsze te *Ogólne*.

Btw. Czy Ty, jako Koordynator, dostajesz powiadomienia o moich edycjach? Wtedy mógłbym bez skrupułów psuć Twoje poprawki bez pytania, bo byś sobie zawsze mógł revertnąć ;)

**Comment by Cracert** [comment]
OK, zmieniłem na **Ogólne**.

Nie, żadne powiadomienia do mnie nie przychodzą. To jedno z nieszczęść Transifexa - trzeba sprawdzać zmiany ręcznie. Ale zmieniaj spokojnie.
