### ISSUE TITLE
Dialog

### ISSUE THREAD

**Issue by Cracert** [Cracert/QGIS-trans-PL#7]
Termin dotyczy okien dialogowych. Czy nie byłoby najprościej tłumaczyć to po prostu jako 'okno'? 'Okno dialogowe' jest jak dla mnie zbyt długie.
Dialog praw autorskich (#6) brzmi koszmarnie. Problem z tymi 'dialogami' (brrrr...) jest taki, że jest ich dużo i czasem trzeba mocno wgryzać się w kod, żeby dojść do tego o jakim oknie jest mowa.

**Comment by borysiasty** [comment]
+1 dla prostego _okna_ gdzie to możliwe.

**Comment by erpas** [comment]
OK, faktycznie, okno dialogowe jest przydługawe. A może, żeby jednak
jakoś je rozróżnić:
window = okno,
dialog window = okienko ?
Tak, czy inaczej, nie będę więcej używał 'dialogu'.

Radek

**Comment by borysiasty** [comment]
Dla mnie okno dialogowe to takie samo okno, jak główne okno programu i nie widzę potrzeby rozróżniania ich. Jeśli przyjmiemy konwencję, że nadrzędne _okno_ ma swoje _okienko_, to wyskakujący komunikat (QMessageBox) podrzędny do _okienka_ wypadałoby konsekwentnie nazywać _okieneczkiem_ :)

**Comment by Cracert** [comment]
Na razie zamieniłem 'okno dialogowe' na 'okno', ale nadal pozostają jeszcze 3 rodzaje tłumaczeń:
- opisujące konkretnie jakie to okno (np. Właściwości)
- okno
- formularz

Wymaga dokładniejszego przeglądnięcia całego kodu...
