### ISSUE TITLE
Wektor -> Narzędzia geoprocessingu -> Dissolve

### ISSUE THREAD

**Issue by alinager** [Cracert/QGIS-trans-PL#70]
**Po pierwsze** - brak tłumaczenia _Dissolve_ na _Agregacja_
**Po drugie** - brak informacji, że w przypadku gdy na warstwie są zaznaczone obiekty, to tylko one będą agregowane. Wcześniej było okienko do zaptaszkowania (agreguj zaznaczone), teraz nie ma takiej opcji i trzeba pamiętać, że jeśli chcemy zagregować wszystkie obiekty to żadne obiekty nie mogą być zaznaczone. --> może dopisać tę informację za _Warstwa wejściowa_? np. _Warstwa wejściowa (gdy  zaznaczone obiekty, agreguje tylko zaznaczone)_. Nie bardzo mam inny pomysł jak to rozwiązać.
**Po trzecie** - po prawej, przy wyborze warstwy wejściowej jest taka zielona zakręcona strzałka, opisana w dymku jako "Kolejne na tej warstwie" (poniżej).

![image](https://user-images.githubusercontent.com/7859075/34771241-26fdfdf4-f604-11e7-8c2a-981334f3a5eb.png)

Jak się te strzałkę "wprztyknie", to każdy obiekt zapisuje się w nowej warstwie. Nie bardzo wiem, co to ma wspólnego z agregacją (bo nie są to obiekty po agregacji). Mi się ta opcja przez przypadek wprztyknęła i spowodowało to powstanie prawie 400 warstw, z których każda zawierała jeden obiekt z warstwy wejściowej:

![image](https://user-images.githubusercontent.com/7859075/34771449-ed22e27e-f604-11e7-8e98-a11d6f9bb2fe.png)

Może w tym dymku powinien się znaleźć opis "Każdy obiekt zapisz w nowej warstwie" - choć to też trochę mylące, bo nie są to obiekty po agregacji.

**Comment by borysiasty** [comment]
Ad 1) W masterze jest już ok (zresztą zamiast tego jednego, teraz są dwa trochę inne algorytmy, oba nie są podpięte w menu Wektor), natomiast w 2.18 tytuł oraz część napisów w oknie jest nieprzetłumaczalna (i już zawsze będzie, bo dzięki transifeksowi niegdyś rutynowe dodanie tekstu do czegokolwiek poza masterem stało się koszmarem). 

Ad 2) W 2.18 jest globalny checkboks w Geoprocesing -> Opcje -> Ogólne. W masterze jest już w każdym algorytmie.

Ad 3) Zielona strzałka chyba faktycznie nie ma tu sensu, natomiast jest to integralny element wybieraka warstwy wejściowej i znaczy: *Każdy obiekt z warstwy wejściowej przetwarzaj osobno i wynik zapisz do osobnej warstwy*. Poprawiłem w 2.18 i w masterze na *Każdy obiekt przetwarzaj do osobnej warstwy* ("przetwarzaj", a nie "zapisuj", bo, jak zauważyłaś, iteracja po poszczególnych obiektach następuje przed działaniem algorytmu). Ktoś ma lepszy pomysł? W oryginale to brzmi "Iterate over this layer, creating a separate output for every feature in the layer".

Czyli w sumie poprawiłem tylko trzecią uwagę (i parę zupełnie innych stringów przy okazji).
