### ISSUE TITLE
Print composer i Layout

### ISSUE THREAD

**Issue by miszokienka** [Cracert/QGIS-trans-PL#73]
Znalazłem kilka wersji tłumaczeń **Print composer** oraz **Layout**. Oba najczęściej tłumaczone są jako _Wydruk_. Nie warto by było je od siebie odróżnić? Czasem **Layout** jest też tłumaczony jako _Układ_.

Zastanawiam się nad ujednoliceniem. Którą opcję wybrać?
1. Zarówno **Print Composer** jak i **Layout** przetłumaczyć jako _Wydruk_
2. **Print Composer** przetłumaczyć jako _Szablon wydruku_ (lub pokrewny) a **Layout** jako _Wydruk_
3. **Print Composer** przetłumaczyć jako _Wydruk_ a **Layout** jako _Układ wydruku_

**Comment by Cracert** [comment]
Z tych propozycji najbardziej podoba mi się opcja 3. 
@borysiasty ?

**Comment by miszokienka** [comment]
Jeszcze się zastanawiam... A może zostawić **Layout** jako słowo nieprzetłumaczalne? Chyba najlepiej pasuje.

**Comment by erpas** [comment]
Niepytany, ale oddam głos na opcję 3 (Print Composer = Wydruk + Layout = Układ wydruku).

**Comment by borysiasty** [comment]
Na pewno Print Composer to nie *Szablon*, bo szablony to mamy w plikach .qpt.

*Układ* jest przyjętym terminem, więc jak najbardziej tak bym tłumaczył Layout: *układ wydruku*, ewentualnie *układ dokumentu* lub *układ treści* (byle nie na układ strony, bo wydruk może być wielostronicowy). Ale jeśli przez **wydruk** rozumiemy dokument, to niech layoutem będzie **układ wydruku**.

Sam Print Composer to teoretycznie *Edytor wydruku*, ewentualnie *Okno wydruku*, ale wydaje się, że spokojnie możemy go uprościć do **Wydruku**.

Tak więc też skłaniam się ku trzeciej opcji z tą uwagą, że Wydruk jako Print Composer to nie tyle tłumaczenie, co uproszczenie. Jeśli gdzieś trzeba będzie podkreślić, że chodzi o okno, a nie dokument w nim, to bym dodał to słowo *Edytor* lub *Okno*. W tym momencie nie widzę w 2.18 żadnego takiego miejsca, ale nie mam tu 2.99, żeby spojrzeć.

PS. W oknie *Opcji* w zakładce *Wydruk* widzę dwa niezręczne tłumaczenia:

 - [x] Domyślne dla siatki i prowadnic -> proponuję **Domyślne opcje siatki**. Po pierwsze gramatyka, a po drugie nie widzę związku z prowadnicami (ale patrzę w 2.18, niech ktoś jeszcze zerknie w 2.99, pliz) 

 - [ ] Ścieżki wydruku - > proponuję **Ścieżki szablonów wydruku**

**Comment by borysiasty** [comment]
Jeszcze jedno: Mamy aktualnie Wydruki i Raporty. **Print/Wydruk** to prosty dokument (albo jedna strona, albo wiele stron różnej wielkości i orientacji, albo pojedynczy atlas - ale nie można tego połączyć, np. strony tytułowej z atlasem). **Report/Raport** to wielosekcyjny dokument, którego każda sekcja odpowiada pojedynczemu wydrukowi. Na razie raport jest nieco na uboczu, ale docelowo może będzie domyślnym wariantem dokumentu. Stąd też czasem trzeba rozróżniać **print layout** i **report layout**.

Raport i jego sekcje składają się z headera, body i footera. To są całe strony, więc chyba nie tłumaczmy 
ich jako nagłówek i stopka, tylko strona... nie wiem, rozpoczynająca i końcowa?

Więcej: https://north-road.com/2018/01/23/exploring-reports-in-qgis-3-0-the-ultimate-guide/

**Comment by miszokienka** [comment]
Może strona tytułowa i końcowa?

**Comment by Cracert** [comment]
Tytułowa i końcowa brzmi dobrze.

**Comment by borysiasty** [comment]
Większość porobiona
