### ISSUE TITLE
Change logging

### ISSUE THREAD

**Issue by miszokienka** [Cracert/QGIS-trans-PL#74]
Proponuję przetłumaczyć jako **Zmień ustawienia rejestrowania**. Występuje to chociażby we wtyczce _DBManager_. Widzę, że w 2.18 jest to tłumaczone jako **Wersjonowanie**.
Nie używałem nigdy tych ustawień, także może niech się wypowie ktoś, kto jest bardziej doświadczony na tym polu.

**Comment by borysiasty** [comment]
To jest właśnie pułapka Transifeksa, który mocno utrudnia dotarcie do kontekstu źródłowego tekstu.
Change logging oznacza tu **rejestrowanie zmian** (czyli inaczej **wersjonowanie**), a nie *zmień rejestrowanie*. 

Mamy dwa wystąpienia: pozycja menu w DBManagerze ``&Change Logging…`` oraz tytuł okienka, które się otworzy po jej wybraniu ``Add Change Logging Support to a Table``.

Proponuję:

 - [x] ``&Change Logging…`` -> **&Wersjonowanie…** (uwaga na przeklejenie znaku trzykropka zamiast 
wstawienia trzech znaków kropek - jesteśmy typograficznie poprawni ;) )

 - [x] ``Add Change Logging Support to a Table`` -> hmm... chyba po prostu **Włącz wersjonowanie tabeli**. Bardziej dosłownie byłoby *Obejmij tabelę kontrolą wersji*, ale to chyba przekombinowane.

Chodzi tu o objęcie wersjonowaniem wybranej tabeli w PostGISie poprzez dodanie do niej dodatkowych kolumn z timestampami i utworzenie triggerów, dzięki czemu podczas edycji tabeli wartości atrybutów nie będą modyfikowane, tylko będą dodawane kolejne kopie rekordów jako nowe wersje. Prawdziwa tabela rośnie z każdą edycją, ale użytkownik widzi ją odfiltrowaną tak, aby zawierała jedynie rekordy albo aktualne na teraz, albo w dowolnym momencie w przeszłości.

**Comment by borysiasty** [comment]
Zmieniłem jak wyżej proponowałem. Zamykam - jeśli ktoś ma uwagi, to reopen prosz.
