### ISSUE TITLE
Wprowadzić moderację wsteczną edycji i przeszkolić tłumaczy.

### ISSUE THREAD

**Issue by borysiasty** [Cracert/QGIS-trans-PL#76]
Słuchajcie, nie nadążam poprawiać świeżo wprowadzanych błędów w tłumaczeniach. Tłumaczenie w Transifeksie (w odróżnieniu od Linguista) wymaga dwóch podstawowych rzeczy:
     - odszukania w kodzie kontekstu, w jakim dany tekst wystąpił
     - sprawdzenia u siebie lokalnie, co z tego wyszło

Tymczasem mamy rosnącą liczbę tłumaczy, którzy tłumaczą na ślepo, wprowadzając absurdalne teksty i  psując wizerunek programu, który chyba chcemy pozycjonować jako profesjonalny. 

Do tego dochodzą bezsensowne automatyczne importy Transifeksa (np. tuż przed wydaniem 3.0 zepsuł tytuł panelu mapy podglądowej i teraz mamy tam "Wprowadzenie" - tekst wzięty z zupełnie innego projektu). Dlatego trzeba:

1. Napisać skrypt, który wyciągnie ostatnie zmiany w celu:
    - wstecznej moderacji,
    - backportowania tłumaczeń do gałęzi 3.0 oraz
    - ogólnego panowania nad sytuacją.

2. Rozesłać do wszystkich maila z wyjaśnieniem powagi sytuacji, instrukcją, jak tłumaczyć bezpiecznie i prośbą o pisemną akceptację tych zasad przed dopuszczeniem do tłumaczenia.

**Comment by miszokienka** [comment]
Ja tłumacząc wyszukuję okno w programie, wyszukuję daną frazę w Transifeksie, a następnie filtruję wszystkie wyrażenia (te przetłumaczone i nieprzetłumaczone) według Occurrence i dopiero zabieram się za tłumaczenie danego okna, tak by pasowało tłumaczenie. Na ślepo mogą rzeczywiście kompletne bzdury powstawać. Tłumaczenie bez kontekstu nie ma sensu.

**Comment by borysiasty** [comment]
Wiem, Robert za Ciebie poręczył ;) Niestety Transifex zachęca do drogi na skróty, a do tego nie udostępnia żadnego wersjonowania, więc nawet nie widać, że coś ostatnio przybyło. Dlatego takie "przeszkolenie" i zobowiązanie się do ostrożności jest niezbędne. A w razie czego będzie podstawą do batożenia.

**Comment by borysiasty** [comment]
Ok, skrypt ma znacznie większy priorytet niż przeszkolenie tłumaczy, bo część (większość?) wandalizmów wprowadza Transifex automatyznie (np. wczoraj tuż przed wydaniem 3.0 przetłumaczył tytuł panelu mapy podglądowej na "Wprowadzenie" i przypisał tę zmianę Milenie :) )

**Comment by miszokienka** [comment]
Trochę nie na temat pytanie, ale nie ma gdzie zadać. Dziś w wersji 3.1.0 nightly widzę, że jest mnóstwo nieprzetłumaczonych tektów w Menadżerze wydruków. Sam je tłumaczyłem jakieś 3 tygodnie temu, w Transifexie widnieją jako przetłumaczone, ale jednak w programie są oryginalne teksty. Jaka może być tego przyczyna?

**Comment by borysiasty** [comment]
A możesz podać jakiś konkretny przykład, to go prześledzę. Mam kilka pomysłów i szkoda czasu się w ciemno rozpisywać. Któregoś wieczora w tym tygodniu zamierzam usiąść i to uporządkować.

**Comment by miszokienka** [comment]
Chociażby tutaj (po wejściu w wydruk):
![przechwytywanie](https://user-images.githubusercontent.com/26738097/37028662-2ec77072-2135-11e8-97d6-28ae36642748.PNG)
Jest jednak wiele takich miejsc. Próbowałem też tłumaczyć teksty w algorytmach (te po prawej stronie po wybraniu konkretnego algorytmu), ale wielu z nich nie mogę odnaleźć w Transifexie.

**Comment by borysiasty** [comment]
Co do Układów, to potwierdzam problem z windowsowymi buildami: to samo widzę w wydanym 3.0.0. Podmieniłem plik qgis_pl.qm na własnoręcznie zbudowany i jest ok. Nie mam pojęcia, o co chodzi. Skrypt budujący nie powinien brać starego tłumaczenia, bo najstarsze dostępne dla niego zawiera już te przetłumaczone teksty. Może coś z kodowaniem i nie podoba mu się trzykropek w oryginalnych tekstach, bo w dwóch przypadkach, w których użyte są trzy pojedyncze kropki ("Menedżer wydruków..." i "Drukuj..."), działa dobrze. Tzn. na pewno tekst w słowniku pasuje do tekstu oryginalnego i nie ma nigdzie rozjazdu trzykropek - trzy kropki, tylko z jakiegoś powodu teksty z trzykropkiem nie są identyfikowane. Ale równocześnie te dwa teksty są najstarsze, więc może jednak skądś wyciągnął nieaktualny plik. Trzeba dalej pogooglać, czy w innych językach też był ten problem i ktoś już coś z tym robi - ja teraz nie dam rady.

Natomiast te teksty w algorytmach nie podlegają tłumaczeniom. Pochodzą z pliku https://github.com/qgis/QGIS/blob/master/python/plugins/processing/algs/help/qgis.yaml
i nie wiem, jaka będzie jego przyszłość. Ponieważ trochę dublują sieciowy help dostępny pod przyciskiem "Pomoc", to może docelowo będą stamtąd importowane i nikt nie chce w nie teraz inwestować.

**Comment by borysiasty** [comment]
No więc oskryptowałem ściąganie różnic, ale wymiękam - od wydania 3.0 zmieniono około 500 tekstów, które trzeba żmudnie wyśledzić w plikach źródłowych, żeby ocenić zasadność tłumaczenia.

Nawet zbacportowanie do 3.0.1 bez weryfikacji będzie strasznie czasochłonne. Ja tego czasu nie mam niestety, chyba trzeba odpuścić serię 3.0 z braku mocy przerobowych.

PS. @miszokienka, generalnie zamiast pisać nie na temat, po prostu otwieraj nowe issue ;)

**Comment by Cracert** [comment]
@miszokienka zwrócił uwagę na ważny problem, więc jest to jak najbardziej na temat moim zdaniem. Jeśli faktycznie jest tak, że tłumaczenia z Transifexa nie lądują w ostatnich kompilacjach mastera, to jest problem. 

Musimy chyba ustalić priorytety, bo wszystkiego nie zrobimy. Rozumiem, że pierwszym kamieniem milowym jest wyprostowanie tłumaczeń w aktualnym LTR czyli 2.18. I to jest zadanie na teraz.
Zadanie drugie (na maj/czerwiec) to przetłumaczenie wersji LTR 3.4.

Tłumaczenie 2.18 i tak musi być robione poza Transifexem, a nad 3.4 musimy się zastanowić.

**Comment by borysiasty** [comment]
@miszokienka, przepraszam za skrót myślowy, śpieszyłem się i niechcący zabrzmiało niemiło. Nawiązałem tylko do Twojego określenia "Trochę nie na temat pytanie, ale nie ma gdzie zadać." Oczywiście, że problem jest ważny i właśnie o to mi chodziło: ten wątek zostanie zamknięty po rozwiązaniu tytułowego problemu, a doklejone do niego problemy pójdą w niepamięć. Dlatego najlepiej jeden temat - jeden wątek. Już zresztą to czynię i przenoszę do nowego wątku: #78, a stąd usuwam.

Na tłumaczenie 2.18 jest już trochę późno :) Jeśli ktoś dałby radę usiąść w ciągu najbliższych 12 dni i podciągnąć nieco 2.18.18 (wydanie 23 marca), to może mieć jakiś tam sens, ale tego dnia wyjdzie pierwsza poprawkowa wersja 3.0.1 i raczej mało kto będzie sięgał po stare 2.18

**Comment by miszokienka** [comment]
@borysiasty Nie zrozumiałem tego w ogóle jako niemiłe, ale jako to, co chciałeś przekazać. Także luzik.
Co do wersji 2.18.18 to jeśli znajdę czas na zajęcie się ta wersją, to odezwę się w tym temacie. Jak to zrobić konkretnie? Tak jak pisałeś w innym issue o QtLinguist?
Ja akurat dalej pracuję w 2.18.17, bo mi się moje projekty z nieznanych mi na razie powodów nie otwierają w 3.0.0. Poza tym QGIS Server na razie mi działa na 2.18 i nie mam czasu sprawdzać, czy wszystko działa sprawnie w 3.0.0 na Ubuntu. Chociaż z drugiej strony nie uważam, żeby tłumaczenie 2.18.18 było niezbędne.

**Comment by borysiasty** [comment]
Tak, Qt Linguistem. Git checkout release-2_18, poprawka i pull request. 

Jeśli linguist ma dostęp do źródeł, to wyświetla pogląd okna (jeśli tekst pochodzi z pliku ui) albo fragment kodu (jeśli pochodzi z pliku cpp). Niestety teksty z plików py (cały Processing) są nienamierzalne i będzie tylko marudził o brakującym (zapewne) pliku python-i18n.cpp.

**Comment by borysiasty** [comment]
@miszokienka: niewykluczone, że w ten weekend i w przyszłym tygodniu będę wrzucał ad hoc różne poprawki do 2.18, więc jeśli też coś będziesz dłubał, to rób częste pull requesty, żeby się niepotrzebnie tego samego nie tłumaczyło, a ewentualne konflikty łatwiej rozwiązywało (zresztą zawsze lepiej pchać często i wcześnie, ja już się parę razy przejechałem na kitraniu zmian przez tydzień u siebie ;) ).

**Comment by borysiasty** [comment]
Od kilku miesięcy nikt niczego nie popsuł, więc zamykam warunkowo :p
