### ISSUE TITLE
W windowsowych buildach (3.0.0 oraz nightbuildach) teksty z trzykropkiem są nieprzetłumaczalne  

### ISSUE THREAD

**Issue by borysiasty** [Cracert/QGIS-trans-PL#78]
@miszokienka pisze:

Dziś w wersji 3.1.0 nightly widzę, że jest mnóstwo nieprzetłumaczonych tektów w Menadżerze wydruków. Sam je tłumaczyłem jakieś 3 tygodnie temu, w Transifexie widnieją jako przetłumaczone, ale jednak w programie są oryginalne teksty. Jaka może być tego przyczyna? Chociażby tutaj (po wejściu w wydruk):

![37028662-2ec77072-2135-11e8-97d6-28ae36642748](https://user-images.githubusercontent.com/1000043/37243126-f7f06124-2474-11e8-96ed-d81ea3972092.PNG)

Jest jednak wiele takich miejsc. (...)

EDIT: Właśnie kompilowałem QGISa na Ubuntu ze źródeł i mam wszystko w tym buildzie przetłumaczone w wydrukach. To jakiś problem chyba z pobieraniem tłumaczenia przy kompilowaniu aplikacji (na tyle, na ile rozumiem to, o czym piszę ;) ).

**Comment by borysiasty** [comment]
Potwierdzam problem z windowsowymi buildami: to samo widzę w wydanym 3.0.0. Podmieniłem plik qgis_pl.qm na własnoręcznie zbudowany i jest ok. 

Przypuszczam, że to problem z kodowaniem znaku trzykropka (który zajmuje trzy bajty w unikodzie i są z nim też inne problemy). Gdzieś po drodze jest na coś konwertowany i w efekcie string źródłowy przestaje pasować do klucza w słowniku z tłumaczeniami. W powyższym menu w dwóch przypadkach, w których użyte są trzy pojedyncze kropki ("Menedżer wydruków..." i "Drukuj..."), wszystko działa dobrze.

Trzeba pogooglać, czy w innych językach też był ten problem i ktoś już coś z tym robi - ja teraz nie dam rady.

**Comment by Cracert** [comment]
A czy to nie jest przypadkiem problem opisany tutaj?

https://lists.osgeo.org/pipermail/qgis-tr/2018-March/000904.html

**Comment by borysiasty** [comment]
Raczej nie. O tym myślałem, pisząc, że trzykropek powoduje też inne problemy, ale on dotyczył tylko tekstów z Pythona (które przechodzą jeszcze przez pylupdate) i skutkował trafianiem tych trzech znaków do Transifeksa. A u nas w Transifeksie (po stronie oyginalnej) jest prawilny trzykropek i w angielskim interfejsie jest trzykropek, a jednak z jakiegoś powodu nie są kojarzone. Dlatego podejrzewam, że podczas wczytywania z dysku jedno z dwojga jest w locie konwertowane.

Ale gadanie gadaniem, czy ktoś mógłby sprawdzić, czy dzisiejszy nightly nadal jest zepsuty? Ja jestem na LTE, poza tym nie chcę już włączać windowsowego kompa :p

**Comment by miszokienka** [comment]
Ja mogę to sprawdzić, ale najwcześniej jutro, a najchętniej dopiero w poniedziałek ☺️ A co do tego, o czym wspomniał @Cracert to jak tłumaczyć ten "specjalny znak wynikający z błędu kodowania". Do tej pory po prostu go kopiowaniem z wersji oryginalnej. Zastępować go trzykropkiem lub trzema kropkami?

**Comment by borysiasty** [comment]
To znaczy te trzy osobne znaki? One już powinny być poprawione, jeszcze gdzieś zostały? Wcześniej ktoś gdzieś pisał, żeby zmieniać na trzykropki lub trzy kropki. Ale teraz chyba nie ma sensu ich tłumaczyć, bo te wersje powinny być martwe.

**Comment by miszokienka** [comment]
OK, właśnie sprawdziłem aktualne windowsowe nightly. W dalszym ciągu jest tak samo, jak na screenie, który wkleiłem wcześniej.

**Comment by miszokienka** [comment]
A właśnie wszedłem w Transifexa i zauważyłem, że są teksty, w których zostały trzy kropki. Są wśród nich teksty z Menadżera wydruków. Niestety mają już status _Reviewed_, więc sam ich nie poprawię. @Cracert - to robota dla Ciebie. Mam wrażenie, że to może pomóc.

**Comment by Cracert** [comment]
Znalazłem 256 fraz z `...` kodowanym jako jeden znak. Spróbuję wkleić go tutaj na przyszłość

`…`

Zmieniam wszystkie wystąpienia na zwykłe trzy kropki.

**Comment by miszokienka** [comment]
Zaraz zaraz!
Z tego co widzę, to trzykropek jako jeden znak jest OK. To trzy kropki jako trzy znaki powodują błędy.

**Comment by Cracert** [comment]
Dopiero zacząłem, więc odwracam zmiany...

**Comment by Cracert** [comment]
Odkręcone. Fraz z trzema kropkami w tłumaczeniu polskim jest 10. Ale wszystkie mają w oryginale też trzy kropki!

Ustawiam je wszystkie na `Unreview`

**Comment by borysiasty** [comment]
Pogubiłem się. 

1. Polskie tłumaczenie nie ma tu nic do rzeczy. Najwyżej wyświetlą się krzaki. ale nie powinno wpływać na rozpoznanie tekstu. Trzykropek jest po prostu preferowany jako poprawny typograficznie. Problem może być tylko z angielskim kluczem. 

2. Na zrzucie @miszokienka poprawnie tłumaczą się teksty z trzema kropkami w oryginale: *Menedżer wydruków* i *Drukuj*, podczas kiedy te z trzykropkiem się nie tłumaczą. Więc trzy kropki są niewinne.

Wszystko to już wyżej opisałem. Tak czy owak nie ma co kombinować, tylko uderzać na listę qgis-tr:
https://lists.osgeo.org/mailman/listinfo/qgis-tr

**Comment by borysiasty** [comment]
Ok, po wygenerowaniu na Linuchu pliku .qm i podstawieniu go w Windowsach wszystko działa. Wygląda na to, że problem z windowsowymi buildami leży więc w plikach .qm.

**Comment by borysiasty** [comment]
@miszokienka, czy ten problem nadal występuje we współczesnych buildach?

**Comment by miszokienka** [comment]
@borysiasty, tak, występuje.

**Comment by borysiasty** [comment]
No to trzeba krzyczeć! Płakać :) Łapać Jurgena na liście dyskusyjnej albo IRC-u/Gitterze. Tylko on coś może pomóc, jeśli problem jest podczas budowy paczek windowsowych. Chyba już kiedyś była o tym dyskusja na listach (link powinien być gdzieś w tym wątku powyżej) - trzeba by zajrzeć, jak się skończyła, może założyć bilet ze szczegółami na issues.qgis.org. Wszyscy podobno używają Windowsów, tylko nie ma komu zakasać rękawów, żeby za rozwiązaniem windowsowych problemów lobbować :)

**Comment by borysiasty** [comment]
Załatwione.
