### ISSUE TITLE
Add Oracle layers with double click

### ISSUE THREAD

**Issue by erpas** [Cracert/QGIS-trans-PL#8]
Dwie opcje w zakładce _Źródła danych_ mają niespójne tłumaczenie:
_Add PostGIS layers with double click and select in extended mode_
_Add Oracle layers with double click and select in extended mode_

Pierwsza tłumaczona jako:
_Uprość wybór i dodawanie warstw PostGIS_
a druga bardziej dosłownie:
_Dodaj warstwy Oracle podwójnym klinięciem itd._

**Comment by borysiasty** [comment]
Pierwsze zupełnie nie zdradza, co się pod nim kryje (zwłaszcza że - jak widzę - nie ma tooltipa).

**Comment by Cracert** [comment]
Zmienione tak jak dla Oracle.
