### ISSUE TITLE
Wpasuj raster

### ISSUE THREAD

**Issue by borysiasty** [Cracert/QGIS-trans-PL#80]
**Align rasters**, czyli uspójnij CRS, rozdzielczość i zasięg kilku warstw do parametrów warstwy wzorcowej [1] jest przetłumaczone jako **Wpasuj raster**. W życiu bym się nie domyślił, że o to chodzi :) Any ideas?

[1] https://docs.qgis.org/2.18/en/docs/user_manual/working_with_raster/raster_analysis.html#raster-alignment

**Comment by alinager** [comment]
Może **Spasuj rastry**? :)

**Comment by borysiasty** [comment]
Harmonizuj? Albo **Harmonizacja rastrów** - to jest akcja w menu *raster* tuż pod akcją **Kalkulator rastra** oraz tytuł okna, więc może nie musi być czasownikowo. Btw. *Kalkulator rastra* też mógłby być w liczbie mnogiej (rastrów, nie kalkulatory :) )

Albo jakiś synonim: https://synonim.net/synonim/harmonizacja

**Comment by erpas** [comment]
Może *Dopasuj cechy rastra*?

**Comment by borysiasty** [comment]
Dałem **Harmonizacja rastrów**.
