### ISSUE TITLE
Wbudowane widżety w legendzie

### ISSUE THREAD

**Issue by borysiasty** [Cracert/QGIS-trans-PL#84]
@miszokienka

 1. Detal - zastanawiam się, czy nie lepiej by brzmiało **Widżety osadzone w legendzie**? Może nie. 
 2. Na pewno dałbym krótko **Dostępne** i **Użyte** (nie *używane*, bo to sugeruje, że suwak jest używany, a nie nowy). 
 3. *Suwak krycia* jakoś dziwacznie wygląda... ;) Może **suwak przezroczystości warstwy**? W tym miejscu chyba możemy bezkarnie zamienić krycie na przezroczystość. 

![zrzut_20180322_210641](https://user-images.githubusercontent.com/1000043/37795549-0f4af5a6-2e15-11e8-8103-cd97ead71427.png)

**Comment by alinager** [comment]
ad. 1. A może wystarczy po prostu **Widżety legendy**? 
ad. 2. Proponuję ewentualnie **Zastosowane** zamiast **Użyte**
ad. 3. Popieram

**Comment by miszokienka** [comment]
1. **Widżety osadzone w legendzie** brzmi nieźle. **Widżety legendy** to właśnie wydawało mi się od początku trochę za mało i myląco. Legenda jest też w wydruku, jak i w ustawieniach serwera WMS/WFS. Chyba, że **Widzety w panelu legendy**?
2. Używany suwak nie jest nowy powiadasz? ;) Ja jestem otwarty na zmianę. **Dostępne** i **Użyte** mi pasuje.
3. Zdecydowanie jestem na tak. Nie miałem pomysłu na ten tekst.

**Comment by borysiasty** [comment]
@miszokienka poprawisz? Trzeba zamykać i otwierać kolejne ;)

**Comment by miszokienka** [comment]
Poprawiłem.

**Comment by borysiasty** [comment]
Można zamknąć?
