### ISSUE TITLE
Zarządzaj prowadnicami

### ISSUE THREAD

**Issue by alinager** [Cracert/QGIS-trans-PL#86]
Brak tłumaczenia **Manage Guides** (menu _Widok_ w oknie Wydruku). Proponuję **Zarządzaj prowadnicami**. Przerzuca nas to do okienka, gdzie możemy dodawać i usuwać prowadnice oraz ustalać ich położenie.

![image](https://user-images.githubusercontent.com/7859075/37823146-e94b7b54-2e88-11e8-8a5b-ce150a01fb3b.png)

**Comment by borysiasty** [comment]
Czy pan w Okienku Zarządzania Prowadnicami nazywa _się Prowadnicowy_?

**Comment by miszokienka** [comment]
Generalnie w wydrukach przetłumaczyłem prawie wszystko. Tutaj wydaje się, że to ten problem, o którym pisaliśmy w innym issue - z (nie)pobieraniem niektórych stringów do builda Windowsowego. Na Ubuntu zdaje się mam to przetłumaczone (nie mam teraz jak sprawdzić).

**Comment by borysiasty** [comment]
Dokładnie, duplikat #78
