### ISSUE TITLE
Dodaj obiekt (wydruki i raporty)

### ISSUE THREAD

**Issue by alinager** [Cracert/QGIS-trans-PL#87]
Proponuję poprawić tłumaczenia w menu _Dodaj obiekt_ (w oknie wydruku i raportu) i zastosować odmianę przez przypadki dla dodawanych obiektów oraz pisownię z małej litery (ewentualnie), czyli:

_Dodaj Mapa_ -> **Dodaj mapę**
_Dodaj Etykieta_ -> **Dodaj etykietę**
_Dodaj Legenda_ -> **Dodaj legendę**
_Dodaj Podziałka_ -> **Dodaj podziałkę**
_Dodaj Strzałka_ -> **Dodaj strzałkę**
_Dodaj Tabela atrybutów_ -> **Dodaj tabelę atrybutów**

oraz przy dodawaniu kształtów: 
_Dodaj prostokątny_ -> **Prostokąt**
_Dodaj eliptyczny_ -> **Elipsa**
_Dodaj Trójkąt_ -> **Trójkąt**

a przy dodawaniu obiektów węzłowych:
_Dodaj poligon_ -> **Poligon**
_Dodaj Polilinia_ ->**Polilinia**

Rozumiem, że teraz to są skróty myślowe od "Dodaj obiekt Mapa, Etykieta itd", ale nie wygląda to za dobrze... 

![image](https://user-images.githubusercontent.com/7859075/37824704-c861c772-2e8d-11e8-9142-391b0ba46525.png)
![image](https://user-images.githubusercontent.com/7859075/37824745-ecbf79f2-2e8d-11e8-9100-023f4e2d0cf1.png)

**Comment by miszokienka** [comment]
Tutaj to wynika z tego, że to są tak naprawdę dwa złączone stringi. Osobno jest tłumaczone **Dodaj**, a osobno pozostałe elementy. Podejrzewam, że jeśli tutaj byśmy zmienili na **mapę** to w innym miejscu może wyskoczyć ten string i nie pasować.

**Comment by borysiasty** [comment]
Miś ma rację. Sprawdziłem i te teksty to są *visibleName* obiektów z *layoutItemGuiRegistry* -  czyli jest duża szansa, że gdzieś pokazują się samodzielnie jako jakieś tytuły albo tooltipy. A jeśli jeszcze się nie pokazują, to w każdej chwili mogą być użyte. Nawet przez wtyczki.

Więc może usuńmy słowo *Dodaj*? Wystarczy w kontekście *QgsLayoutDesignerDialog* tłumaczyć ``Add %1`` jako samo ``%1``:

![zrzut_20180323_134523](https://user-images.githubusercontent.com/1000043/37829718-7546cc0a-2ea0-11e8-8123-18af04be1c13.png)
*(uwaga: zrzut poglądowy, w Transifeksie jest jeszcze po staremu)*

Efekty uboczne są IMHO pomijalne. Ten jeden tekst obsługuje: 
 - akcje menu Dodaj obiekt
 - nazwy dwóch podmenu i akcji w nim
 - odpowiadające im dwa rozwijalne klawisze i akcje w nich.

Nie ma zaś wpływu na nazwę głównego menu "Dodaj obiekt". Tooltipy klawiszy są brane z nazwy odpowiedniego podmenu (**Kształt** i **Obiekt węzłowy**), więc tym się różnią od tooltipów wszystkich sąsiednich klawiszy (**Dodaje...** w trzeciej osobie), ale jako **Dodaj** też się różniły.

**Comment by borysiasty** [comment]
Co do **prostokątny, eliptyczny i Trójkąt**, to występują w  dwóch kontekstach:

 1) *QgsLayoutShapeWidget* (albo inaczej: w pliku *qgslayoutshapewidget.cpp* - nie pamiętam, co tam Transifex pokazuje). To też jest visibeName w rejestrze obiektów, więc zmieniłbym rzeczownikowo na **Prostokąt** i **Elipsa**

 2) *QObject* (*qgslayoutapputils.cpp*) - lista rozwijalna we *Właściwościach elementu* (trzeba najpierw dodać dowolny z trójki). Tu też lepiej wygląda mi rzeczownikowo.

**UWAGA**: Nie ruszajcie *prostokątny* i *eliptyczny* z kontekstu *QgsTextFormatWidgetBase*, bo to jest od tła etykiety. Tam z kolei bym przy okazji poprawił *Kwadratowy* na *kwadratowy* i *Bufor* na *bufor* (duża litera na małą), żeby było spójnie.

**Comment by borysiasty** [comment]
Zmieniłem jak proponowałem.
