### ISSUE TITLE
Multi band color (byte/band)

### ISSUE THREAD

**Issue by erpas** [Cracert/QGIS-trans-PL#9]
W Opcjach, zakładka Renderowanie, opcje dotyczące rastrów wielobarwnych:
_Multi band color (byte/band)_
_Multi band color (>byte/band)_

mogą być doszlifowane przez zmianę wartości w nawiasach:

_Kolor wielokanałowy (bajt/kanał)_  - przez co rozumie się 8 bitów na kanał
_Kolor wielokanałowy (>bajt/kanał)_  - przez co rozumie się więcej niż 8 bitów na kanał

**Comment by Cracert** [comment]
Słuszna uwaga - poprawione.
