### ISSUE TITLE
Locator (aka Ósmy pasażer QGIS-a)

### ISSUE THREAD

**Issue by borysiasty** [Cracert/QGIS-trans-PL#91]
Czy zostawiamy nazwę własną **Locator**, czy wymyślamy np. **Szukacz** albo **Wyszukiwanie**? Ta nazwa pada w  oknie Opcji: 
 - nazwa zakładki *Locator*
 - tekst *Locator filters* (to akurat można przetłumaczyć i bez tłumaczenia nazwy własnej)

**Comment by borysiasty** [comment]
Aha, pierwowzór z QtCreatora jest przetłumaczony na nasze na **Lokalizator**. Szału nie ma...

**Comment by miszokienka** [comment]
Na ten moment wpisuję **Wyszukiwanie**.

**Comment by borysiasty** [comment]
@ALL zamykamy?
