### ISSUE TITLE
Actions (filtr Locatora)

### ISSUE THREAD

**Issue by borysiasty** [Cracert/QGIS-trans-PL#92]
Jednym z filtrów Lokatora jest "Actions" (alias ``.``), czyli polecenia menu i pasków narzędzi. Dla przykładu, wpisanie ``. Warstwy`` spowoduje uruchomienie akcji Widok -> Panele -> Warstwy, czyli ukrycie panelu warstw.

Aktualnie to jest przetłumaczone na **Akcje**, ale ze względu na mylące podobieństwo z akcjami na mapie otwieram burzę mózgów, jak to inaczej na nasze przełożyć.

**Comment by borysiasty** [comment]
Akcje menu? Obawiam się, że dla nieprogramujących w Qt w ogóle termin *akcja* się nie kojarzy...

**Comment by alinager** [comment]
Może "Działania (w) menu"?

**Comment by borysiasty** [comment]
![](https://blaskicodziennosci.files.wordpress.com/2017/01/sweterek.jpg?w=300&h=197)

**Comment by borysiasty** [comment]
Przełknąłbym może łatwiej *pozycje menu*... ;-)

**Comment by borysiasty** [comment]
Daję ``Akcje (pozycje menu)``.
