### ISSUE TITLE
Narzędzia geoprocessingu

### ISSUE THREAD

**Issue by miszokienka** [Cracert/QGIS-trans-PL#95]
Potłumaczyłem ostatnio trochę brakujących fraz i z tego co widzę, to chyba zepsułem w menu _Wektor_ > _Narzędzia geoprocessingu_ (teraz są _Algorytmy processingu_). W wersji 3.2.2 są _Narzędzia geoprocessingu_, w  3.3 dev są _Algorytmy processingu_.
Pytanie do Borysa: jedyne co znalazłem w Transifeksie, to Twoja zmiana 8 sierpnia i dochodzę do wniosku, że to jednak nie ja i że to zamierzona zmiana?
Wg mnie lepiej brzmiało to wcześniej.

**Comment by borysiasty** [comment]
@miszokienka: Nie bardzo Cię rozumiem. W menu ``Wektor`` chyba są i były ``Narzędzia processingu`` (przez dwa s), ja natomiast zmieniłem tytuł panelu Processingu (w sensie nazwy własnej całego frameworku ``Processing``) z ``Narzędzi geoprocesingu`` (przez jedno s) na ``Algorytmy processingu``. Właściwie powinienem napisać z dużej litery ``Algorytmy Processingu``.
 
Jeśli chodzi o menu Wektor, to IMHO tam jest bałagan. Nazwa ``Narzędzia processingu`` pochodzi z czasów fToolsów, gdy nie było jeszcze frameworku Processing, natomiast dzisiaj jest do niego myląco podobna. Z Twojego pytania wnoszę, że w jakiś sposób wiążesz ten processing z Processingiem? Ja nie widzę związku, bo przecież również inne "grupy narzędzi" z tego menu zawierają narzędzia/algorytmy Processingu, chociaż w innym podziale, niż w panelu. Szczerze mówiąc dość nielogicznym dla mnie (zresztą podobnie jak w panelu), dlatego nigdy nie zaglądam do tego menu, tylko używam filtra w panelu. Tak czy owak najlepiej byłoby uniknąć tutaj słowa *processing*, żeby się nie myliło z ``Processingiem``.

Jeśli chodzi o nazwę panelu, to dyskutowaliśmy to jakiś czas temu i stanęło na tym. Po pierwsze zrezygnowaliśmy z tłumaczenia ``Processing`` na *Geoprocesing* (przez jedno s), bo nazwa oryginalna pojawia się w wielu miejscach - nazwach wtyczek, katalogów, angielskich tekstach, a przede wszystkim w nazwie głównej wtyczki: przecież "włącz wtyczkę Processing, aby odblokować panel Geoprocesingu" wprowadza niepotrzebny zamęt. Dlatego zdecydowaliśmy się pozostać przy nazwie własnej.

Natomiast jeśli chodzi o narzędzia, to w Processingu chyba nigdzie nie pada słowo *tool* i chyba tylko w jednym miejscu słowo *toolbox*. Natomiast panel Processingu składa się z samych *algorytmów* i to określenie jest bardzo mocno wrośnięte w Processing. Zatem jest to - było nie było - panel *algorytmów*, a użycie słowa *narzędzia* było niespójne.

Ot i cała tajemnica zmiany. Jeśli Cię nie przekonuje, to możemy przedyskutować powrót do starej wersji. Wyjścia są dwa:
a) Processing zawiera **algorytmy**, a **narzędzia** to są mapowe (tak jak teraz).
b) Processing zawiera **narzędzia**, które są implementacjami czy też interfejsami **algorytmów** (czyli statystyczny Kowalski ma w ręku narzędzie i nie interesuje go, że w środku pracuje algorytm)

Dobrze by było podjąć decyzję przed 3.4 :) 
CC @all

**Comment by miszokienka** [comment]
OK Borys, już rozumiem dlaczego zmiana i przychylam się do niej. U mnie aktualnie w menu `Wektor` jest tak:
![wektor](https://user-images.githubusercontent.com/26738097/44643537-27746a80-a9d1-11e8-8bc3-163a99af282d.png)
Napisałem tutaj, bo miałem wrażenie, że przed moimi ostatnimi edycjami były tam `Narzędzia processingu`, a nie `Algorytmy processingu` i że to ja coś pozmieniałem. Teraz wychodzi na to, że mi się tylko wydawało, więc Issue jest do zamknięcia i nic nie trzeba z tym robić ;)

No, chyba że powinny tam być `Narzędzia processingu`.

**Comment by borysiasty** [comment]
No nieeee, tutaj jest *Geoprocessing Tools*, co oczywiście powinno być tłumaczone na ``Narzędzia processingu`` (a właściwie geoprocesingu). Jedyne wystąpienie tekstu ``Algorytmy Processingu`` powinno być w menu Processing (*Processing Toolbox*). 

Faktycznie Transifex twierdzi, ze ja to zmieniłem niedawno. Albo się jakoś bardzo rąbnąłem (szczerze wątpię, bo zwykle patrzę, co robię), albo sam sobie tak zaimportował i ogłosił mnie autorem. Dokładnie tak samo kilka godzin przed wydaniem 3.0 przemianował *Panel Podglądu* na *Wprowadzenie* i napisał, że to Milena zmieniła. Okazało się, że zaimportował jakiś stary tekst z zupełnie innego projektu, gdzie faktycznie Milena przetłumaczyła overview na wprowadzenie - tylko że w zupełnie innym kontekście.

Najlepsze, że w Debianie mam dobrze... Poprawiam zatem w Transifeksie:

**Geoprocessing Tools** -> **Narzędzia geoprocesingu** (forma spolszczona i z geo)
**Processing Toolbox**  -> **Algorytmy Processingu** (z dużej litery, jako nazwa własna)

**Comment by borysiasty** [comment]
Sprostowanie: ``Algorytmy Processingu`` (oryg. *Processing Toolbox*) to tylko tytuł panelu. Włącznik (pierwsza pozycja menu Processing) nazywa się ``Panel algorytmów`` (oryg. *Toolbox*)

**Comment by borysiasty** [comment]
Ok, już wszystko jasne. 

Nie mam pojęcia, skąd tu się wziął ten tekst. Transifex faktycznie twierdzi, ze ja go zmieniłem. Albo się  bardzo rąbnąłem (szczerze wątpię, bo zwykle patrzę, co robię), albo sam sobie coś zaimportował i ogłosił mnie autorem. Dokładnie tak samo kilka godzin przed wydaniem 3.0 przemianował *Panel Podglądu* na *Wprowadzenie* i przypisał zmianę Milenie :) Okazało się, że zaimportował jakiś stary tekst z zupełnie innego projektu, gdzie faktycznie Milena przetłumaczyła overview na wprowadzenie - tylko że w zupełnie innym kontekście. Te automatyczne importy w połączeniu z brakiem jakiegokolwiek logowania zmian (nie mówiąc już o moderacji czy kontroli wersji) są porażające.

Zatem ostatecznie dałem tak:

 - **&Geoprocessing Tools** -> **Narzędzia &geoprocesingu** (to menu z Twojego zrzutu; dodałem "geo" i spolszczyłem podwójne s)
 - **Processing Toolbox**  -> **Algorytmy Processingu** (tytuł panelu; dałem z dużej litery, jako nazwę własną)
 - **&Toolbox**  -> **Panel &algorytmów** (pierwsza pozycja w menu Processing)
 
UWAGA UWAGA: Skróty do algorytmów instalują się w menu Wektor i Raster w **domyślnych** podmenu, a potem użytkownik może je zmieniać - to znaczy może przesuwać poszczególne narzędzia/algorytmy w inne miejsca w całym menu. Przy pierwszym uruchomieniu QGIS-a 3 do ustawień wpisują się te domyślne ścieżki (dostępu w ramach menu), więc jeśli użytkownik uruchomił pierwszy raz QGIS-a 3 z tymi "algorytmami" zamiast "narzędzi", to tak mu się zapisało. Zatem po poprawieniu tłumaczeń trzeba zresetować te zapamiętane położenia, żeby się odtworzyły z nowych domyślnych wartości! 

Aby je zresetować, trzeba wejść w menu ``Ustawienia`` -> ``Opcje`` -> ``Processing`` -> ``Menu``. Tam jest wielki klawisz ``Przywróć domyślne``. Mam wrażenie, ze naciskanie go nic nie dawało, dopóki nie rozwinąłem choćby pierwszej z brzegu gałęzi: ``QGIS native c++`` -> ``Agreguj``. Akurat ten algorytm jest w interesującej nas gałęzi, więc od razu widać, czy zaskoczyło. Czyli: rozwinąłem gałąź, wcisnąłem przycisk, przeładowałem QGIS-a i zaskoczyło. Najpierw oczywiście wgrałem świeży plik qm.

**Comment by borysiasty** [comment]
To jest chyba już rozpracowane. Pozostaje kwestia przymusowej kapitalizacji we wszystkich językach, ale to już inny temat.
