### ISSUE TITLE
Wielkie litery w menu Wektor i Raster

### ISSUE THREAD

**Issue by borysiasty** [Cracert/QGIS-trans-PL#96]
Processing, wstawiając swoje algorytmy do menu Wektor, wersalikuje (majuskulizuje? :-) ) pierwsze litery (już po przetłumaczeniu, więc Transifeks nie ma nic do gadania):

![aaakapitalizacja](https://user-images.githubusercontent.com/1000043/44620919-5a1d4680-a89d-11e8-8a9b-0d83254952e1.png)

Ktoś tak wymyślił, że po angielsku będzie dobrze, ale po naszemu jest kaszana. Nie wiem, czy dam radę się tym zająć przed wydaniem 3.4, więc ochotnik potrzebny do założenia ticketu i pomęczeniu ludzi na liście qgis-developer. 

@ALL

**Comment by miszokienka** [comment]
Jak mi powiesz jak to się robi, to mogę się tym zająć ;) Zwłaszcza, że mam jeszcze jedną propozycję dotyczącą dokowalnego okienka stylu warstwy - dobrze by było mieć możliwość z jego poziomu zapisywać i ładować style w bazie danych PostgreSQL.

**Comment by borysiasty** [comment]
Trzeba by zacząć od założenia ticketa na issues.qgis.org (albo wykopaniu istniejącego, jeśli taki jest) i przydzieleniu go Alexowi Bruyowi, bo nikt inny się tym na pewno nie zajmie, a potem lobbować, lobbować, lobbować! :) Może sam zdążę się za to zabrać - szczerze mówiąc prawdopodobnie znacznie mniej czasu zajmie mi naprawa, niż myślenie, kogo i jak ścigać... :)

Co do stylu warstwy, zgadzam się w pełni. Te opcje zapisu/odczytu w panelu są boleśnie niekompletne. A z kolei te kompletne w oknie właściwości warstwy są strasznie zakitrane. Myślałem też o dodaniu ich do podręcznego podmenu warstwy *Style* - skoro można kopiować i wklejać, to aż się prosi dodać możliwość wczytania i zapisu. Pisałem o tym w #97. Mam to na optymistycznej liście poprawek do zrobienia w pierwszej połowie września (czyli na kilka dni przed feature freeze - trochę kiepsko).

**Comment by miszokienka** [comment]
OK, co do stylu warstwy to zgłosiłem issue jako feature request. Tzn. wszystko wskazuje na to, że mi się udało to zrobić :) Tego z literkami na razie nie zgłosiłem, bo może zdążysz :P

**Comment by borysiasty** [comment]
Super! Idealnie! Tak trzymać. Oczywiście musiałem coś od siebie dodać ;-p
Z literkami w końcu też założyłem ticketa i napisałem na qgis-community-team, bo okazało się, że za cienki jestem w rumuńskim i dialektach portugalskiego. 

Podoba mi się idea unifikacji avatarów - to pozwala podkreślić cechy szczególne.

**Comment by borysiasty** [comment]
Zamykam, a akcja przenosi się do traca.

**Comment by borysiasty** [comment]
@miszokienka, poprawka właśnie trafiła do mastera. 

Please note all the algorithm menu entries are saved in QSettings, thus once they got capitalized and saved, this commit won't fix them automatically. You need to run Settings -> Options -> Processing -> Menu -> Restore defaults in order to regenerate them without capitalization.

**Comment by miszokienka** [comment]
I to będzie działać w menu `Wektor`, tak? Tzn. nie będzie tam zmieniać na wielkie pierwszych, dobrze rozumiem?

**Comment by borysiasty** [comment]
Tak, w menu Wektor, Raster i w tytułach okien algorytmów. Z powyższym zastrzeżeniem, że trzeba zrestorować diflolty.
