### ISSUE TITLE
Relacja przestrzenna "within"

### ISSUE THREAD

**Issue by borysiasty** [Cracert/QGIS-trans-PL#98]
Lewe to **contains**, prawe to **within**. Zacząłem zmieniać na ``zawiera się w``, ale może po prostu dać krótko ``wewnątrz``? Na marginesie: tuż niżej jest ``równe`` - może lepiej ``tożsame``?

![zrzut_20180911_171829](https://user-images.githubusercontent.com/1000043/45369957-70d6d380-b5e7-11e8-8800-3a7356fb545c.png)

**Comment by Cracert** [comment]
`wewnątrz` i `tożsame` są lepsze; w takich miejscach zostawiałbym też źródła `przecina (intersects)`, bo jest na to miejsce

**Comment by borysiasty** [comment]
Within zrobione, pozostały nawiasy ze źródłami przy pozostałych relacjach.

**Comment by borysiasty** [comment]
Gotowe. Uffff, to był długi tydzień.
