### ISSUE TITLE
Tekst rozdzielany przecinkami

### ISSUE THREAD

**Issue by borysiasty** [Cracert/QGIS-trans-PL#99]
Przedmiotowa nazwa zakładki w *Zarządzaniu źródłami danych* jest strasznie długa i wcale nie mam przekonania, czy dla przeciętnego użytkownika jest bardziej zrozumiała niż krótkie **CSV**. Osobiście bym to chyba tak właśnie nazwał, a może ktoś ma jakiś pośredni wariant? W oryginale jest *Delimited Text*.

![zrzut_20180928_205113](https://user-images.githubusercontent.com/1000043/46227703-51b6a080-c360-11e8-8718-914987aae2b9.png)

**Comment by miszokienka** [comment]
Ustawiłem jako _Tekst rozdzielany przecinkami_ ze względu na tłumaczenie. Też mi bardziej pasowało po prostu **CSV** lub **Plik CSV**, bo faktycznie brzmi to znacznie bardziej intuicyjnie.

**Comment by Cracert** [comment]
Słuszna uwaga Borys.
Jestem za **Plik CSV**.

**Comment by borysiasty** [comment]
**Plik CSV** brzmi fajnie, tylko zastanawiam się, czy użycie słowa *plik* jest spójne z resztą. Najpierw mamy krótko: Raster, Wektor i Mesh, potem ten jedyny Plik, a potem tylko nazwy własne. Przy czym te trzy elementy powyżej CSV tworzą jedną grupę, wszystko poniżej też można zaszufladkować jako *połączenia*, więc CSV jest tu singlem i wyróżniająca się nazwa ma uzasadnienie. 

Właśnie, jak tłumaczymy mesh? Wie ktoś, czy jest przyjęty polski termin? @erpas? Na pewno unikałbym tu słowa Plik, bo jeśli będą dwa pliki, to również Raster powinien być Plikiem rastrowym ;)

**Comment by miszokienka** [comment]
Czuję się w pełni przekonany i jestem za krótkim **CSV** :)

**Comment by miszokienka** [comment]
Zmienione na **CSV**.
